// WhichAnimalToday — Archive List (Framer code component)
//
// Paste into a Framer code component for the Archive page. Fully
// self-contained, no dependency on the game component's code.
//
// SETUP: if Framer's starter template uses a named export instead of
// `export default`, rename this function to match.
//
// Uses the same field-journal design tokens as GameComponent.tsx —
// keep them in sync if the palette/type changes.

const ARCHIVE_JSON_URL =
  "https://raw.githubusercontent.com/28-Anon/whichanimaltoday/master/data/archive.json";

// CSSProperties is imported as a type rather than reached through a `React.`
// namespace: Framer's code editor doesn't reliably have that namespace in
// scope, so `React.CSSProperties` fails to compile on paste.
import { useEffect, useState, type CSSProperties } from "react";

// ===== BEGIN GENERATED ENGINE — do not edit by hand =====
// Generated by scripts/generateFramerEngine.ts — do not edit by hand.
// Run `npm run generate:framer` after changing any of:
//   src/stats.ts
//   src/gameState.ts
//   src/journal.ts
// `npm test` and CI both fail when this block drifts from src/.

// --- from src/stats.ts ---

interface Stats {
  played: number;
  wins: number;
  /** Integer 0-100. 0 when nothing has been played. */
  winPercent: number;
  currentStreak: number;
  maxStreak: number;
  /** Wins on guess 1, 2, and 3 respectively. */
  distribution: [number, number, number];
  /** Days that offered a bonus round and were played. */
  bonusRounds: number;
  /** Of those, the ones the player got right. */
  bonusHits: number;
}

const MS_PER_DAY = 24 * 60 * 60 * 1000;

/** Whole days since the epoch for a YYYY-MM-DD UTC date string. */
function dayNumber(date: string): number {
  return Math.floor(new Date(`${date}T00:00:00Z`).getTime() / MS_PER_DAY);
}

function computeStats(history: DailyResult[], today: string): Stats {
  const sorted = [...history].sort((a, b) => a.date.localeCompare(b.date));

  const played = sorted.length;
  const wins = sorted.filter((entry) => entry.solved).length;
  const winPercent = played === 0 ? 0 : Math.round((wins / played) * 100);

  const distribution: [number, number, number] = [0, 0, 0];
  for (const entry of sorted) {
    if (entry.solved && entry.guessesUsed >= 1 && entry.guessesUsed <= 3) {
      distribution[entry.guessesUsed - 1] += 1;
    }
  }

  // Walk the history once, tracking the run of solved entries on
  // consecutive calendar days. `run` ends up holding the streak that
  // terminates at the most recent entry.
  let maxStreak = 0;
  let run = 0;
  let previous: DailyResult | null = null;
  for (const entry of sorted) {
    if (!entry.solved) {
      run = 0;
    } else if (
      previous !== null &&
      previous.solved &&
      dayNumber(entry.date) - dayNumber(previous.date) === 1
    ) {
      run += 1;
    } else {
      run = 1;
    }
    if (run > maxStreak) maxStreak = run;
    previous = entry;
  }

  // A streak is only alive if the player has actually shown up recently.
  // Nothing is written on days they don't play, so absence has to be
  // detected by comparing against today rather than by a stored counter.
  let currentStreak = 0;
  const last = played === 0 ? null : sorted[played - 1];
  if (last !== null && last.solved) {
    const gap = dayNumber(today) - dayNumber(last.date);
    if (gap === 0 || gap === 1) currentStreak = run;
  }

  // Only the two known values count, so a hand-edited storage value can
  // neither inflate the tally nor throw.
  let bonusRounds = 0;
  let bonusHits = 0;
  for (const entry of sorted) {
    if (entry.bonus === "hit") {
      bonusRounds += 1;
      bonusHits += 1;
    } else if (entry.bonus === "miss") {
      bonusRounds += 1;
    }
  }

  return {
    played,
    wins,
    winPercent,
    currentStreak,
    maxStreak,
    distribution,
    bonusRounds,
    bonusHits,
  };
}

// --- from src/gameState.ts ---

interface StorageLike {
  getItem(key: string): string | null;
  setItem(key: string, value: string): void;
}

interface DailyResult {
  date: string;
  puzzleNumber: number;
  solved: boolean;
  guessesUsed: number;
  /**
   * Absent when the day offered no bonus round. Deliberately does NOT bump
   * SCHEMA_VERSION: `loadState` maps an unrecognised version to an empty
   * history, so a bump would wipe every existing player's stats. An optional
   * field is read correctly by the v2 loader, and a pre-bonus entry having no
   * value here is accurate rather than missing.
   */
  bonus?: "hit" | "miss";
}

const SCHEMA_VERSION = 2;

const STORAGE_KEY = "whichanimaltoday_state";

interface StoredStateV2 {
  version: 2;
  history: DailyResult[];
}

/** The pre-2026-07-29 shape, read only during migration. */
interface StoredStateV1 {
  lastResult: DailyResult | null;
  currentStreak: number;
}

function emptyState(): StoredStateV2 {
  return { version: SCHEMA_VERSION, history: [] };
}

/**
 * A malformed entry (e.g. `null`, or missing/mistyped fields) would
 * otherwise pass the `Array.isArray` check below and then throw later
 * inside `computeStats` (`a.date.localeCompare`) — which, in the Framer
 * component, gets swallowed by the fetch `.catch` and bricks the game on
 * every load thereafter, since nothing ever clears the bad stored value.
 * Filtering here lets a corrupt value self-heal instead.
 */
function isWellFormedEntry(entry: unknown): entry is DailyResult {
  if (typeof entry !== "object" || entry === null) return false;
  const candidate = entry as Partial<DailyResult>;
  return (
    typeof candidate.date === "string" &&
    typeof candidate.solved === "boolean" &&
    typeof candidate.guessesUsed === "number"
  );
}

function loadState(storage: StorageLike): StoredStateV2 {
  let raw: string | null;
  try {
    raw = storage.getItem(STORAGE_KEY);
  } catch {
    // Storage can throw outright rather than return null: blocked cookies
    // and Safari private mode make even reading a SecurityError. Degrade to
    // an empty history so every stat reads zero.
    return emptyState();
  }
  if (!raw) return emptyState();

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return emptyState();
  }
  if (typeof parsed !== "object" || parsed === null) return emptyState();

  const candidate = parsed as Partial<StoredStateV2> & Partial<StoredStateV1>;

  if (candidate.version === SCHEMA_VERSION) {
    return Array.isArray(candidate.history)
      ? {
          version: SCHEMA_VERSION,
          history: candidate.history.filter(isWellFormedEntry),
        }
      : emptyState();
  }

  // v1 -> v2. `currentStreak` is deliberately dropped: the number is known
  // but the days that produced it are not, so it cannot become real
  // history. See spec §2 "Accepted loss".
  if ("lastResult" in candidate) {
    const last = candidate.lastResult;
    return { version: SCHEMA_VERSION, history: last ? [last] : [] };
  }

  return emptyState();
}

function saveState(storage: StorageLike, state: StoredStateV2): void {
  try {
    storage.setItem(STORAGE_KEY, JSON.stringify(state));
  } catch {
    // Quota exceeded, or storage blocked entirely. Nothing to recover: the
    // player gets a fresh game on each load and their stats stay at zero.
    // Throwing here would crash the game the moment they finish a puzzle.
  }
}

function getHistory(storage: StorageLike): DailyResult[] {
  return loadState(storage).history;
}

function getLastResult(storage: StorageLike): DailyResult | null {
  const history = loadState(storage).history;
  if (history.length === 0) return null;
  const sorted = [...history].sort((a, b) => a.date.localeCompare(b.date));
  return sorted[sorted.length - 1];
}

function getCurrentStreak(
  storage: StorageLike,
  today: string
): number {
  return computeStats(loadState(storage).history, today).currentStreak;
}

function getStats(storage: StorageLike, today: string): Stats {
  return computeStats(loadState(storage).history, today);
}

function recordResult(
  storage: StorageLike,
  result: DailyResult
): number {
  // Idempotent by date: re-recording the same day replaces that entry
  // rather than appending, so a double-fire can't inflate `played`.
  const history = loadState(storage).history.filter(
    (entry) => entry.date !== result.date
  );
  history.push(result);
  history.sort((a, b) => a.date.localeCompare(b.date));

  saveState(storage, { version: SCHEMA_VERSION, history });

  // The result being recorded is by definition today's.
  return computeStats(history, result.date).currentStreak;
}

function hasPlayedToday(
  storage: StorageLike,
  today: string
): boolean {
  return loadState(storage).history.some((entry) => entry.date === today);
}

// --- from src/journal.ts ---

type JournalState = "starred" | "identified" | "missed";

interface ArchivedAnimal {
  puzzleNumber: number;
  date: string;
  slug: string;
  commonName: string;
  species?: string;
  imageUrl: string;
}

interface JournalEntry {
  date: string;
  puzzleNumber: number;
  commonName: string;
  species?: string;
  imageUrl: string;
  slug: string;
  state: JournalState;
}

interface JournalSummary {
  entries: JournalEntry[];
  /** Includes starred entries — a star is an identification plus extra. */
  identified: number;
  starred: number;
  total: number;
}

/**
 * Joins what was featured (the archive) with what the player solved (local
 * history) on DATE.
 *
 * Date, never `puzzleNumber` arithmetic: `getTodayPuzzleIndex` wraps modulo
 * the animal list length, so adding a single animal would re-map every past
 * day and silently rewrite this journal with the wrong creatures. The archive
 * is a record of what actually happened and stays true as the list grows.
 *
 * This function only ever reads. The history it consumes lives under the key
 * holding the player's streak and stats, and `loadState` maps an unrecognised
 * version to an empty history — so a write from here could erase the very
 * record the journal exists to display.
 */
function buildJournal(
  archive: ArchivedAnimal[],
  history: DailyResult[]
): JournalSummary {
  const empty: JournalSummary = { entries: [], identified: 0, starred: 0, total: 0 };
  if (history.length === 0) return empty;

  const byDate = new Map(history.map((entry) => [entry.date, entry]));

  // Days before the player's first play are not gaps they failed to fill,
  // and a wall of grey is a bleak first impression for a newcomer.
  const firstPlayed = history
    .map((entry) => entry.date)
    .reduce((earliest, date) => (date < earliest ? date : earliest));

  const entries: JournalEntry[] = archive
    .filter((animal) => animal.date >= firstPlayed)
    .map((animal) => {
      const result = byDate.get(animal.date);

      // A bonus miss is still an identification. The bonus is additive by
      // design and must never cost the player the entry.
      const state: JournalState = !result?.solved
        ? "missed"
        : result.bonus === "hit"
          ? "starred"
          : "identified";

      return {
        date: animal.date,
        puzzleNumber: animal.puzzleNumber,
        commonName: animal.commonName,
        ...(animal.species ? { species: animal.species } : {}),
        imageUrl: animal.imageUrl,
        slug: animal.slug,
        state,
      };
    })
    .sort((a, b) => b.date.localeCompare(a.date));

  return {
    entries,
    identified: entries.filter((e) => e.state !== "missed").length,
    starred: entries.filter((e) => e.state === "starred").length,
    total: entries.length,
  };
}

// ===== END GENERATED ENGINE =====

interface ArchiveEntry {
  puzzleNumber: number;
  date: string;
  slug: string;
  commonName: string;
  imageUrl: string;
  funFacts: string;
  category: string;
  imageAttribution: string;
}

type LoadState = "loading" | "error" | "ready";

// The generated engine takes a StorageLike so it can be unit-tested against
// a fake. In the browser that is window.localStorage — but the property
// access itself throws when cookies are blocked, and the object does not
// exist during SSR, so both are guarded here rather than inside the engine.
//
// The journal only ever READS. The key it reads holds the player's streak
// and stats, and loadState maps an unrecognised version to an empty history
// — a write from this page could erase the record it exists to display.
const browserStorage: StorageLike = {
  getItem(key) {
    if (typeof window === "undefined") return null;
    try {
      return window.localStorage.getItem(key);
    } catch {
      return null;
    }
  },
  setItem() {
    // Deliberately inert. Nothing on this page may write.
  },
};

const EMPTY_JOURNAL: JournalSummary = {
  entries: [],
  identified: 0,
  starred: 0,
  total: 0,
};

export default function ArchiveListComponent() {
  const [state, setState] = useState<LoadState>("loading");
  const [summary, setSummary] = useState<JournalSummary>(EMPTY_JOURNAL);

  useEffect(() => {
    let cancelled = false;

    fetch(ARCHIVE_JSON_URL)
      .then((res) => {
        if (!res.ok) throw new Error(`Fetch failed: ${res.status}`);
        return res.json();
      })
      .then((data: ArchiveEntry[]) => {
        if (cancelled) return;
        // buildJournal orders newest-first itself and drops days from before
        // the player started, so no pre-sort or slicing is needed here.
        setSummary(buildJournal(data, getHistory(browserStorage)));
        setState("ready");
      })
      .catch(() => {
        if (!cancelled) setState("error");
      });

    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <div style={styles.page}>
      <header style={styles.header}>
        <div style={styles.wordmark}>Field Journal</div>
        <div style={styles.tagline}>every specimen you have identified</div>
      </header>

      {state === "ready" && summary.total > 0 && (
        <div style={styles.progress}>
          {summary.identified} of {summary.total} identified
          {summary.starred > 0 && <span> · {summary.starred} ⭐</span>}
        </div>
      )}

      {state === "loading" && <div style={styles.statusText}>Loading past specimens…</div>}
      {state === "error" && (
        <div style={styles.statusText}>Couldn't load the archive. Please refresh.</div>
      )}
      {state === "ready" && summary.total === 0 && (
        <div style={styles.statusText}>
          Your journal is empty. Identify today's specimen and it gets
          stamped in here.
        </div>
      )}

      {state === "ready" && summary.total > 0 && (
        <div style={styles.grid}>
          {summary.entries.map((entry) => (
            <a
              key={entry.slug}
              // encodeURIComponent, not raw interpolation: a slug containing
              // &, # or a space would otherwise break the query parameter.
              // Slugs are generated from curated names so this is currently
              // unreachable, but it's the correct call regardless.
              href={`/archive-detail?slug=${encodeURIComponent(entry.slug)}`}
              style={styles.card}
            >
              <img
                src={entry.imageUrl}
                alt={entry.commonName}
                // Greyed rather than hidden: the player already saw the
                // answer on the reveal card, so hiding it is fake mystery.
                // A named gap is the mechanic.
                // The archive grows by one entry a day and has no pagination,
                // so without this a visitor eventually requests hundreds of
                // images on a single page load.
                loading="lazy"
                style={{
                  ...styles.thumb,
                  ...(entry.state === "missed" ? styles.thumbMissed : null),
                }}
              />
              <div style={styles.cardName}>
                {entry.commonName}
                {entry.state === "starred" && " ⭐"}
              </div>
              {/* Never colour alone — the greyed cards carry a text label
                  for the same reason the bonus round carries ✓ and ✗. */}
              <div style={styles.cardMeta}>
                {entry.state === "missed"
                  ? "not identified"
                  : "#" + entry.puzzleNumber + " · " + entry.date}
              </div>
            </a>
          ))}
        </div>
      )}
    </div>
  );
}

const tokens = {
  paper: "#FBF3E7",
  paperCard: "#FFFDF8",
  ink: "#2B2420",
  inkSoft: "#6B5F52",
  coral: "#E8623D",
  line: "#E3D5BE",
  display: "'Fraunces', Georgia, serif",
  body: "'Inter', system-ui, -apple-system, sans-serif",
  mono: "'IBM Plex Mono', ui-monospace, SFMono-Regular, monospace",
};

const styles: Record<string, CSSProperties> = {
  progress: {
    fontFamily: tokens.mono,
    fontSize: 14,
    color: tokens.ink,
    textAlign: "center",
    marginBottom: 18,
  },
  thumbMissed: {
    filter: "grayscale(1)",
    opacity: 0.45,
  },
  page: {
    fontFamily: tokens.body,
    background: tokens.paper,
    color: tokens.ink,
    maxWidth: 720,
    margin: "0 auto",
    padding: "24px 20px 40px",
  },
  header: {
    marginBottom: 20,
  },
  wordmark: {
    fontFamily: tokens.display,
    fontSize: 24,
    fontWeight: 600,
  },
  tagline: {
    fontFamily: tokens.mono,
    fontSize: 11,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: tokens.inkSoft,
    marginTop: 2,
  },
  statusText: {
    color: tokens.inkSoft,
    textAlign: "center",
    padding: "40px 0",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))",
    gap: 14,
  },
  card: {
    display: "block",
    background: tokens.paperCard,
    border: `1px solid ${tokens.line}`,
    borderRadius: 6,
    padding: 8,
    textDecoration: "none",
    color: tokens.ink,
  },
  thumb: {
    width: "100%",
    aspectRatio: "1 / 1",
    objectFit: "cover",
    borderRadius: 4,
    marginBottom: 6,
    display: "block",
  },
  cardName: {
    fontFamily: tokens.body,
    fontWeight: 600,
    fontSize: 13,
  },
  cardMeta: {
    fontFamily: tokens.mono,
    fontSize: 10,
    color: tokens.inkSoft,
    marginTop: 2,
  },
};
