// WhichAnimalToday — Archive List (Framer code component)
//
// Paste into a Framer code component for the Archive page. Fully
// self-contained, no dependency on the game component's code.
//
// SETUP: if Framer's starter template uses a named export instead of
// `export default`, rename this function to match.
//
// Uses the same field-journal design tokens as GameComponent.tsx —
// keep them in sync if the palette/type changes.

const ARCHIVE_JSON_URL =
  "https://whichanimaltoday.whichanimaltoday.workers.dev/archive.json";

// The archive job writes the *previous* day at 00:15 UTC, so archive.json
// never contains today. Fetching the animal list too lets the journal show
// today's entry the moment it is solved, rather than the next morning.
const ANIMALS_JSON_URL =
  "https://whichanimaltoday.whichanimaltoday.workers.dev/animals.json";

// Must match framer/GameComponent.tsx and scripts/runDailyArchive.ts.
const LAUNCH_DATE = new Date("2026-08-01T00:00:00Z");

// CSSProperties is imported as a type rather than reached through a `React.`
// namespace: Framer's code editor doesn't reliably have that namespace in
// scope, so `React.CSSProperties` fails to compile on paste.
import { useEffect, useState, type CSSProperties } from "react";

// ===== BEGIN GENERATED ENGINE — do not edit by hand =====
// Generated by scripts/generateFramerEngine.ts — do not edit by hand.
// Run `npm run generate:framer` after changing any of:
//   src/stats.ts
//   src/gameState.ts
//   src/puzzleIndex.ts
//   src/journal.ts
// `npm test` and CI both fail when this block drifts from src/.

// --- from src/stats.ts ---

interface Stats {
  played: number;
  wins: number;
  /** Integer 0-100. 0 when nothing has been played. */
  winPercent: number;
  currentStreak: number;
  maxStreak: number;
  /** Wins on guess 1, 2, and 3 respectively. */
  distribution: [number, number, number];
  /** Days that offered a bonus round and were played. */
  bonusRounds: number;
  /** Of those, the ones the player got right. */
  bonusHits: number;
}

const MS_PER_DAY = 24 * 60 * 60 * 1000;

/** Whole days since the epoch for a YYYY-MM-DD UTC date string. */
function dayNumber(date: string): number {
  return Math.floor(new Date(`${date}T00:00:00Z`).getTime() / MS_PER_DAY);
}

function computeStats(history: DailyResult[], today: string): Stats {
  const sorted = [...history].sort((a, b) => a.date.localeCompare(b.date));

  const played = sorted.length;
  const wins = sorted.filter((entry) => entry.solved).length;
  const winPercent = played === 0 ? 0 : Math.round((wins / played) * 100);

  const distribution: [number, number, number] = [0, 0, 0];
  for (const entry of sorted) {
    if (entry.solved && entry.guessesUsed >= 1 && entry.guessesUsed <= 3) {
      distribution[entry.guessesUsed - 1] += 1;
    }
  }

  // Walk the history once, tracking the run of solved entries on
  // consecutive calendar days. `run` ends up holding the streak that
  // terminates at the most recent entry.
  let maxStreak = 0;
  let run = 0;
  let previous: DailyResult | null = null;
  for (const entry of sorted) {
    if (!entry.solved) {
      run = 0;
    } else if (
      previous !== null &&
      previous.solved &&
      dayNumber(entry.date) - dayNumber(previous.date) === 1
    ) {
      run += 1;
    } else {
      run = 1;
    }
    if (run > maxStreak) maxStreak = run;
    previous = entry;
  }

  // A streak is only alive if the player has actually shown up recently.
  // Nothing is written on days they don't play, so absence has to be
  // detected by comparing against today rather than by a stored counter.
  let currentStreak = 0;
  const last = played === 0 ? null : sorted[played - 1];
  if (last !== null && last.solved) {
    const gap = dayNumber(today) - dayNumber(last.date);
    if (gap === 0 || gap === 1) currentStreak = run;
  }

  // Only the two known values count, so a hand-edited storage value can
  // neither inflate the tally nor throw.
  let bonusRounds = 0;
  let bonusHits = 0;
  for (const entry of sorted) {
    if (entry.bonus === "hit") {
      bonusRounds += 1;
      bonusHits += 1;
    } else if (entry.bonus === "miss") {
      bonusRounds += 1;
    }
  }

  return {
    played,
    wins,
    winPercent,
    currentStreak,
    maxStreak,
    distribution,
    bonusRounds,
    bonusHits,
  };
}

// --- from src/gameState.ts ---

interface StorageLike {
  getItem(key: string): string | null;
  setItem(key: string, value: string): void;
}

interface DailyResult {
  date: string;
  puzzleNumber: number;
  solved: boolean;
  guessesUsed: number;
  /**
   * Absent when the day offered no bonus round. Deliberately does NOT bump
   * SCHEMA_VERSION: `loadState` maps an unrecognised version to an empty
   * history, so a bump would wipe every existing player's stats. An optional
   * field is read correctly by the v2 loader, and a pre-bonus entry having no
   * value here is accurate rather than missing.
   */
  bonus?: "hit" | "miss";
}

const SCHEMA_VERSION = 2;

const STORAGE_KEY = "whichanimaltoday_state";

interface StoredStateV2 {
  version: 2;
  history: DailyResult[];
}

/** The pre-2026-07-29 shape, read only during migration. */
interface StoredStateV1 {
  lastResult: DailyResult | null;
  currentStreak: number;
}

function emptyState(): StoredStateV2 {
  return { version: SCHEMA_VERSION, history: [] };
}

/**
 * A malformed entry (e.g. `null`, or missing/mistyped fields) would
 * otherwise pass the `Array.isArray` check below and then throw later
 * inside `computeStats` (`a.date.localeCompare`) — which, in the Framer
 * component, gets swallowed by the fetch `.catch` and bricks the game on
 * every load thereafter, since nothing ever clears the bad stored value.
 * Filtering here lets a corrupt value self-heal instead.
 */
function isWellFormedEntry(entry: unknown): entry is DailyResult {
  if (typeof entry !== "object" || entry === null) return false;
  const candidate = entry as Partial<DailyResult>;
  return (
    typeof candidate.date === "string" &&
    typeof candidate.solved === "boolean" &&
    typeof candidate.guessesUsed === "number"
  );
}

function loadState(storage: StorageLike): StoredStateV2 {
  let raw: string | null;
  try {
    raw = storage.getItem(STORAGE_KEY);
  } catch {
    // Storage can throw outright rather than return null: blocked cookies
    // and Safari private mode make even reading a SecurityError. Degrade to
    // an empty history so every stat reads zero.
    return emptyState();
  }
  if (!raw) return emptyState();

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return emptyState();
  }
  if (typeof parsed !== "object" || parsed === null) return emptyState();

  const candidate = parsed as Partial<StoredStateV2> & Partial<StoredStateV1>;

  if (candidate.version === SCHEMA_VERSION) {
    return Array.isArray(candidate.history)
      ? {
          version: SCHEMA_VERSION,
          history: candidate.history.filter(isWellFormedEntry),
        }
      : emptyState();
  }

  // v1 -> v2. `currentStreak` is deliberately dropped: the number is known
  // but the days that produced it are not, so it cannot become real
  // history. See spec §2 "Accepted loss".
  if ("lastResult" in candidate) {
    const last = candidate.lastResult;
    return { version: SCHEMA_VERSION, history: last ? [last] : [] };
  }

  return emptyState();
}

function saveState(storage: StorageLike, state: StoredStateV2): void {
  try {
    storage.setItem(STORAGE_KEY, JSON.stringify(state));
  } catch {
    // Quota exceeded, or storage blocked entirely. Nothing to recover: the
    // player gets a fresh game on each load and their stats stay at zero.
    // Throwing here would crash the game the moment they finish a puzzle.
  }
}

function getHistory(storage: StorageLike): DailyResult[] {
  return loadState(storage).history;
}

function getLastResult(storage: StorageLike): DailyResult | null {
  const history = loadState(storage).history;
  if (history.length === 0) return null;
  const sorted = [...history].sort((a, b) => a.date.localeCompare(b.date));
  return sorted[sorted.length - 1];
}

function getCurrentStreak(
  storage: StorageLike,
  today: string
): number {
  return computeStats(loadState(storage).history, today).currentStreak;
}

function getStats(storage: StorageLike, today: string): Stats {
  return computeStats(loadState(storage).history, today);
}

function recordResult(
  storage: StorageLike,
  result: DailyResult
): number {
  // Idempotent by date: re-recording the same day replaces that entry
  // rather than appending, so a double-fire can't inflate `played`.
  const history = loadState(storage).history.filter(
    (entry) => entry.date !== result.date
  );
  history.push(result);
  history.sort((a, b) => a.date.localeCompare(b.date));

  saveState(storage, { version: SCHEMA_VERSION, history });

  // The result being recorded is by definition today's.
  return computeStats(history, result.date).currentStreak;
}

function hasPlayedToday(
  storage: StorageLike,
  today: string
): boolean {
  return loadState(storage).history.some((entry) => entry.date === today);
}

// --- from src/puzzleIndex.ts ---

/** Anything carrying the daily-rotation flag. */
interface DailyCandidate {
  /** Absent means eligible. Only ever written as `false`. */
  dailyEligible?: boolean;
}

/**
 * The animals allowed to appear as a daily puzzle.
 *
 * Some animals cannot be a daily puzzle because no clue makes a player produce
 * their name — Chowsingha, Ibisbill, Bald Uacari. Those are not hard puzzles,
 * they are guaranteed losses, and a loss ends a streak.
 *
 * Timer mode deliberately keeps using the unfiltered list: it is multiple
 * choice, so spelling never arises and an unspellable animal is still a fair
 * question there. `scripts/orderAnimals.ts` writes the excluded ones after the
 * eligible ones, so filtering here never disturbs an already-played day.
 */
function selectDailyAnimals<T extends DailyCandidate>(
  animals: readonly T[]
): T[] {
  return animals.filter((animal) => animal.dailyEligible !== false);
}

function utcDayNumber(date: Date): number {
  const utcMidnight = Date.UTC(
    date.getUTCFullYear(),
    date.getUTCMonth(),
    date.getUTCDate()
  );
  return Math.floor(utcMidnight / MS_PER_DAY);
}

function getDaysSinceLaunch(today: Date, launchDate: Date): number {
  return utcDayNumber(today) - utcDayNumber(launchDate);
}

function getTodayPuzzleIndex(
  today: Date,
  launchDate: Date,
  listLength: number
): number {
  if (listLength <= 0) {
    throw new Error("listLength must be greater than 0");
  }
  const daysSinceLaunch = getDaysSinceLaunch(today, launchDate);
  return ((daysSinceLaunch % listLength) + listLength) % listLength;
}

/**
 * Milliseconds until the next puzzle. Puzzles roll over at UTC midnight —
 * `getTodayPuzzleIndex` counts UTC days — so this must work off UTC and not
 * the visitor's local midnight, or the countdown would be wrong by the
 * viewer's timezone offset.
 *
 * At exactly midnight this returns a full day rather than zero: the puzzle
 * that just appeared is today's, and the next one is 24 hours out.
 */
function msUntilNextUtcMidnight(now: Date): number {
  // Day + 1 overflows correctly into the next month or year; Date.UTC
  // normalises it.
  const nextMidnight = Date.UTC(
    now.getUTCFullYear(),
    now.getUTCMonth(),
    now.getUTCDate() + 1
  );
  return nextMidnight - now.getTime();
}

/** A duration as `HH:MM:SS`, floored to the second and never negative. */
function formatCountdown(milliseconds: number): string {
  const totalSeconds = Math.max(0, Math.floor(milliseconds / 1000));
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;
  const pad = (value: number) => String(value).padStart(2, "0");
  return `${pad(hours)}:${pad(minutes)}:${pad(seconds)}`;
}

// --- from src/journal.ts ---

type JournalState = "starred" | "identified" | "missed";

interface ArchivedAnimal {
  puzzleNumber: number;
  date: string;
  slug: string;
  commonName: string;
  species?: string;
  imageUrl: string;
}

interface JournalEntry {
  date: string;
  puzzleNumber: number;
  commonName: string;
  species?: string;
  imageUrl: string;
  slug: string;
  state: JournalState;
}

interface JournalSummary {
  entries: JournalEntry[];
  /** Includes starred entries — a star is an identification plus extra. */
  identified: number;
  starred: number;
  total: number;
}

/**
 * Joins what was featured (the archive) with what the player solved (local
 * history) on DATE.
 *
 * Date, never `puzzleNumber` arithmetic: `getTodayPuzzleIndex` wraps modulo
 * the animal list length, so adding a single animal would re-map every past
 * day and silently rewrite this journal with the wrong creatures. The archive
 * is a record of what actually happened and stays true as the list grows.
 *
 * This function only ever reads. The history it consumes lives under the key
 * holding the player's streak and stats, and `loadState` maps an unrecognised
 * version to an empty history — so a write from here could erase the very
 * record the journal exists to display.
 */
function buildJournal(
  archive: ArchivedAnimal[],
  history: DailyResult[],
  today?: ArchivedAnimal
): JournalSummary {
  const empty: JournalSummary = { entries: [], identified: 0, starred: 0, total: 0 };
  if (history.length === 0) return empty;

  const byDate = new Map(history.map((entry) => [entry.date, entry]));

  // `runDailyArchive` writes the *previous* day at 00:15 UTC, so `archive`
  // never contains today. Without this a player solved today's puzzle, opened
  // the journal, and found nothing new — at exactly the moment the feature
  // exists to hook them, and on a new player's very first visit.
  //
  // Three conditions, each load-bearing:
  //
  // - `today` is supplied. Callers without it get the previous behaviour
  //   exactly, so nothing that only has an archive has to change.
  // - The player has a result for that date. A day still in progress is not a
  //   day they failed, and including it would stamp it "missed" hours early.
  // - The archive does not already cover the date. Tomorrow the job writes the
  //   real entry; keying on date collapses the two rather than showing the day
  //   twice, and the archive wins because it is the authoritative record of
  //   what was actually featured.
  const covered = new Set(archive.map((animal) => animal.date));
  const featured =
    today && byDate.has(today.date) && !covered.has(today.date)
      ? [...archive, today]
      : archive;

  // Days before the player's first play are not gaps they failed to fill,
  // and a wall of grey is a bleak first impression for a newcomer.
  const firstPlayed = history
    .map((entry) => entry.date)
    .reduce((earliest, date) => (date < earliest ? date : earliest));

  const entries: JournalEntry[] = featured
    .filter((animal) => animal.date >= firstPlayed)
    .map((animal) => {
      const result = byDate.get(animal.date);

      // A bonus miss is still an identification. The bonus is additive by
      // design and must never cost the player the entry.
      const state: JournalState = !result?.solved
        ? "missed"
        : result.bonus === "hit"
          ? "starred"
          : "identified";

      return {
        date: animal.date,
        puzzleNumber: animal.puzzleNumber,
        commonName: animal.commonName,
        ...(animal.species ? { species: animal.species } : {}),
        imageUrl: animal.imageUrl,
        slug: animal.slug,
        state,
      };
    })
    .sort((a, b) => b.date.localeCompare(a.date));

  return {
    entries,
    identified: entries.filter((e) => e.state !== "missed").length,
    starred: entries.filter((e) => e.state === "starred").length,
    total: entries.length,
  };
}

// ===== END GENERATED ENGINE =====

interface ArchiveEntry {
  puzzleNumber: number;
  date: string;
  slug: string;
  commonName: string;
  /**
   * Optional because the archive predates it: entries written before the
   * content pass carry no species, and five of the twelve days on record have
   * one. `buildJournal` passes it through when it is there.
   */
  species?: string;
  imageUrl: string;
  funFacts: string;
  category: string;
  imageAttribution: string;
}

type LoadState = "loading" | "error" | "ready";

/** Only the fields today's stand-in entry needs from `animals.json`. */
interface TodaysAnimal {
  commonName: string;
  imageUrl: string;
  species?: string;
  dailyEligible?: boolean;
}

/**
 * The archive entry today *would* have, if the job had already run.
 *
 * `runDailyArchive` writes the previous day at 00:15 UTC, so a player who
 * solved today's puzzle used to open the journal and find nothing new — on a
 * new player's very first visit, at exactly the moment the feature exists to
 * hook them.
 *
 * This is computed only for **today**. Deriving past days from the same
 * arithmetic would be a serious mistake: `getTodayPuzzleIndex` wraps modulo the
 * list length, so adding a single animal would silently re-map every historic
 * date and rewrite the journal with the wrong creatures. The archive stays the
 * authoritative record of what actually happened; this fills one gap at the
 * front, and `buildJournal` drops it the moment the real entry arrives.
 *
 * Returns undefined rather than throwing when the list is unavailable or the
 * date precedes launch — the journal then behaves exactly as it did before.
 */
function todaysEntry(
  animals: TodaysAnimal[] | null,
  now: Date
): ArchiveEntry | undefined {
  if (!animals || animals.length === 0) return undefined;

  const daily = selectDailyAnimals(animals);
  if (daily.length === 0) return undefined;

  const puzzleNumber = getDaysSinceLaunch(now, LAUNCH_DATE) + 1;
  if (puzzleNumber < 1) return undefined;

  const animal = daily[getTodayPuzzleIndex(now, LAUNCH_DATE, daily.length)];

  return {
    puzzleNumber,
    date: now.toISOString().slice(0, 10),
    // No slug on purpose: there is no archive record to link to yet. The list
    // reads an empty slug as "send them to the game", where today's reveal is
    // already showing — a better destination than a detail page that would 404.
    slug: "",
    commonName: animal.commonName,
    ...(animal.species ? { species: animal.species } : {}),
    imageUrl: animal.imageUrl,
    funFacts: "",
    category: "",
    imageAttribution: "",
  };
}

// The generated engine takes a StorageLike so it can be unit-tested against
// a fake. In the browser that is window.localStorage — but the property
// access itself throws when cookies are blocked, and the object does not
// exist during SSR, so both are guarded here rather than inside the engine.
//
// The journal only ever READS. The key it reads holds the player's streak
// and stats, and loadState maps an unrecognised version to an empty history
// — a write from this page could erase the record it exists to display.
const browserStorage: StorageLike = {
  getItem(key) {
    if (typeof window === "undefined") return null;
    try {
      return window.localStorage.getItem(key);
    } catch {
      return null;
    }
  },
  setItem() {
    // Deliberately inert. Nothing on this page may write.
  },
};

const EMPTY_JOURNAL: JournalSummary = {
  entries: [],
  identified: 0,
  starred: 0,
  total: 0,
};

/**
 * Framer sizes a code component's frame from these annotations. Without them
 * it defaults to a fixed box, which silently crops the component — that is
 * why the field journal published with its specimen cards sliced off partway
 * down, with nothing wrong in the code and no error anywhere.
 *
 * `auto` height means the frame grows to fit the content, so a journal with
 * forty entries is as tall as it needs to be. `any` width lets the frame be
 * set to Fill, instead of rendering the page in a narrow column with empty
 * space beside it.
 *
 * @framerSupportedLayoutWidth any
 * @framerSupportedLayoutHeight auto
 */
export default function ArchiveListComponent() {
  const [state, setState] = useState<LoadState>("loading");
  const [summary, setSummary] = useState<JournalSummary>(EMPTY_JOURNAL);

  useEffect(() => {
    let cancelled = false;

    const archiveRequest = fetch(ARCHIVE_JSON_URL).then((res) => {
      if (!res.ok) throw new Error(`Fetch failed: ${res.status}`);
      return res.json() as Promise<ArchiveEntry[]>;
    });

    // Deliberately allowed to fail on its own. The animal list is only needed
    // for today's not-yet-archived entry, and a journal missing one day beats
    // a journal that will not load — which is what a shared rejection would
    // produce the first time this URL throttles.
    const animalsRequest = fetch(ANIMALS_JSON_URL)
      .then((res) => (res.ok ? (res.json() as Promise<TodaysAnimal[]>) : null))
      .catch(() => null);

    Promise.all([archiveRequest, animalsRequest])
      .then(([archive, animals]) => {
        if (cancelled) return;
        // buildJournal orders newest-first itself and drops days from before
        // the player started, so no pre-sort or slicing is needed here.
        setSummary(
          buildJournal(
            archive,
            getHistory(browserStorage),
            todaysEntry(animals, new Date())
          )
        );
        setState("ready");
      })
      .catch(() => {
        if (!cancelled) setState("error");
      });

    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <div style={styles.page}>
      {/* The wordmark links back to the journal root. Added in Framer and
          brought back here on 2026-08-03; edits made only in Framer are
          destroyed by the next paste. */}
      <header style={styles.header}>
        <a href="/archive" style={styles.wordmarkLink} aria-label="Field Journal">
          <div style={styles.wordmark}>Field Journal</div>
        </a>
        <div style={styles.tagline}>every specimen you have identified</div>
      </header>

      {state === "ready" && summary.total > 0 && (
        <div style={styles.progress}>
          {summary.identified} of {summary.total} identified
          {summary.starred > 0 && <span> · {summary.starred} ⭐</span>}
        </div>
      )}

      {state === "loading" && <div style={styles.statusText}>Loading past specimens…</div>}
      {state === "error" && (
        <div style={styles.statusText}>Couldn't load the archive. Please refresh.</div>
      )}
      {state === "ready" && summary.total === 0 && (
        <div style={{ ...styles.statusText, ...styles.emptyStateCard }}>
          Your journal is empty. Identify today's specimen and it gets
          stamped in here.
        </div>
      )}

      {state === "ready" && summary.total > 0 && (
        <div style={styles.grid}>
          {summary.entries.map((entry) => (
            <a
              // Date, not slug: today's stand-in entry has no slug yet, and
              // two keyless siblings would collide. Dates are unique per entry
              // by construction — buildJournal deduplicates on them.
              key={entry.date}
              // An empty slug means the archive job has not written this day
              // yet, so there is no detail page to open. Today's reveal is
              // already on the game itself, which is a better destination than
              // a lookup that would find nothing.
              //
              // encodeURIComponent, not raw interpolation: a slug containing
              // &, # or a space would otherwise break the query parameter.
              // Slugs are generated from curated names so this is currently
              // unreachable, but it's the correct call regardless.
              href={
                entry.slug
                  ? `/archive-detail?slug=${encodeURIComponent(entry.slug)}`
                  : "/"
              }
              style={styles.card}
            >
              <img
                src={entry.imageUrl}
                alt={entry.commonName}
                // Greyed rather than hidden: the player already saw the
                // answer on the reveal card, so hiding it is fake mystery.
                // A named gap is the mechanic.
                // The archive grows by one entry a day and has no pagination,
                // so without this a visitor eventually requests hundreds of
                // images on a single page load.
                loading="lazy"
                style={{
                  ...styles.thumb,
                  ...(entry.state === "missed" ? styles.thumbMissed : null),
                }}
              />
              <div style={styles.cardName}>
                {entry.commonName}
                {entry.state === "starred" && " ⭐"}
              </div>
              {/* The specific species, where the record names one. Suppressed
                  when it merely repeats the common name — "Axolotl / Axolotl"
                  reads as a bug rather than as detail. */}
              {entry.species &&
                entry.species.toLowerCase() !== entry.commonName.toLowerCase() && (
                  <div style={styles.cardSpecies}>{entry.species}</div>
                )}
              {/* Never colour alone — the greyed cards carry a text label
                  for the same reason the bonus round carries ✓ and ✗. */}
              <div style={styles.cardMeta}>
                {entry.state === "missed"
                  ? "not identified"
                  : "#" + entry.puzzleNumber + " · " + entry.date}
              </div>
            </a>
          ))}
        </div>
      )}
    </div>
  );
}

const tokens = {
  paper: "#FBF3E7",
  paperCard: "#FFFDF8",
  ink: "#2B2420",
  inkSoft: "#6B5F52",
  coral: "#E8623D",
  line: "#E3D5BE",
  display: "'Fraunces', Georgia, serif",
  body: "'Inter', system-ui, -apple-system, sans-serif",
  mono: "'IBM Plex Mono', ui-monospace, SFMono-Regular, monospace",
};

const styles: Record<string, CSSProperties> = {
  progress: {
    fontFamily: tokens.mono,
    fontSize: 14,
    color: tokens.ink,
    textAlign: "center",
    marginBottom: 18,
  },
  thumbMissed: {
    filter: "grayscale(1)",
    opacity: 0.45,
  },
  // No maxWidth, and margin 0 rather than "0 auto". Both were changed in
  // Framer and brought back here on 2026-08-03: capping the journal at 720px
  // left a band of empty paper beside it inside a wider frame, and the frame
  // is what should decide the width. overflowX guards the grid against
  // pushing a horizontal scrollbar onto the page on a narrow phone.
  page: {
    fontFamily: tokens.body,
    background: tokens.paper,
    color: tokens.ink,
    width: "100%",
    margin: 0,
    padding: "24px 20px 40px",
    boxSizing: "border-box",
    overflowX: "hidden",
  },
  header: {
    marginBottom: 20,
  },
  wordmark: {
    fontFamily: tokens.display,
    fontSize: 24,
    fontWeight: 600,
  },
  tagline: {
    fontFamily: tokens.mono,
    fontSize: 11,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: tokens.inkSoft,
    marginTop: 2,
  },
  wordmarkLink: {
    color: "inherit",
    textDecoration: "none",
    display: "inline-block",
  },
  statusText: {
    color: tokens.inkSoft,
    textAlign: "center",
    padding: "40px 0",
  },
  // A dashed card rather than bare centred text: an empty journal is the
  // first thing a new player sees, and a lone sentence on paper reads as a
  // page that failed to load. From Framer, 2026-08-03.
  emptyStateCard: {
    maxWidth: 540,
    margin: "20px auto 0",
    background: tokens.paperCard,
    border: `1px dashed ${tokens.line}`,
    borderRadius: 8,
    padding: "28px 20px",
    color: tokens.ink,
    lineHeight: 1.5,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))",
    gap: 14,
  },
  card: {
    display: "block",
    background: tokens.paperCard,
    border: `1px solid ${tokens.line}`,
    borderRadius: 6,
    padding: 8,
    textDecoration: "none",
    color: tokens.ink,
  },
  thumb: {
    width: "100%",
    // Square, so the grid stays a grid whatever shape the photographs are.
    aspectRatio: "1 / 1",
    /**
     * `contain` inside that square rather than `cover`, changed 2026-08-13
     * alongside the detail page. Cropping a portrait photograph to a square
     * costs 20% of the seahorse and 46% of the tarsier, and a journal card is
     * a record of an animal the player identified — showing them two thirds of
     * it is a worse trade than a little empty space beside it.
     *
     * The grid does not move: the box is still square, so the letterboxing
     * happens inside the card rather than changing its size.
     */
    objectFit: "contain",
    background: tokens.paper,
    borderRadius: 4,
    marginBottom: 6,
    display: "block",
  },
  cardName: {
    fontFamily: tokens.body,
    fontWeight: 600,
    fontSize: 13,
  },
  cardSpecies: {
    fontFamily: tokens.body,
    fontSize: 11,
    fontStyle: "italic",
    color: tokens.inkSoft,
    marginTop: 1,
  },
  cardMeta: {
    fontFamily: tokens.mono,
    fontSize: 10,
    color: tokens.inkSoft,
    marginTop: 2,
  },
};
