// WhichAnimalToday — Daily Game (Framer code component)
//
// Paste this whole file into a Framer code component. It's fully
// self-contained — Framer's code editor doesn't reliably resolve relative
// imports across multiple pasted files, so the engine is inlined rather
// than imported. That inlined section is GENERATED from src/ by
// scripts/generateFramerEngine.ts: edit src/, then run
// `npm run generate:framer`. Editing it here is overwritten, and both
// `npm test` and CI fail when it drifts. See docs/framer-integration.md.
//
// SETUP — two things to confirm once you paste this in:
// 1. Export style: this uses `export default function`. If Framer's
//    starter template for a new code component uses a named export
//    instead, rename this function to match and drop `export default`.
// 2. For the full intended look (see design notes below), add these
//    fonts in Framer's Site Settings → Fonts: "Fraunces" (display),
//    "Inter" (body), "IBM Plex Mono" (labels/numbers). The fallback
//    stacks below still look reasonable without them.
//
// DESIGN CONCEPT: a naturalist's field journal / specimen card — the
// daily animal is presented like a pinned photograph in a field log,
// with a monospace "FIELD FILE #N" catalog tag, a torn-tape photo
// corner, and a rubber-stamp "IDENTIFIED" reveal. This is the visual
// signature; keep it consistent if you extend the design.
//
// Set this once, matching scripts/runDailyArchive.ts exactly:
const LAUNCH_DATE = new Date("2026-08-01T00:00:00Z");
const ANIMALS_JSON_URL =
  "https://raw.githubusercontent.com/28-Anon/whichanimaltoday/master/data/animals.json";

// Appended to the copied share text on its own line, so a friend who
// receives "WhichAnimalToday #12 🐾 2/3" can actually reach the game.
// Sharing is the primary growth mechanic. No trailing slash and no www:
// this string is pasted verbatim into chat apps, so it stays short.
const SITE_URL = "https://whichanimaltoday.com";

const HOW_TO_PLAY: { heading: string; body: string }[] = [
  {
    heading: "One animal a day.",
    body:
      "Every day, WhichAnimalToday features one new specimen — a photo, waiting to be identified.",
  },
  {
    heading: "1. Look at the photo.",
    body: "No caption, no name — just the picture. What do you think it is?",
  },
  {
    heading: "2. Take your guess.",
    body:
      "Type an animal name and hit \"Guess →\". Common names, scientific names, and close spellings all count — you don't need to nail the exact wording.",
  },
  {
    heading: "3. Get a clue either way.",
    body:
      "Right or wrong, each guess reveals a new clue — starting tricky, ending almost-a-giveaway. You get 3 guesses total.",
  },
  {
    heading: "4. See the reveal.",
    body:
      "Once you guess it — or run out of guesses — the full answer shows up, along with a fun fact and where the photo came from.",
  },
  {
    heading: "5. Share your result.",
    body:
      "Copy your result (something like `WhichAnimalToday #12 🐢 2/3`) and send it to a friend. No spoilers — just your score.",
  },
  {
    heading: "Come back tomorrow",
    body:
      "for a brand new specimen. Miss a day and your streak resets, so try to make it a habit.",
  },
];

// Types are imported explicitly rather than reached through a `React.`
// namespace: Framer's code editor doesn't reliably have that namespace in
// scope, so `React.CSSProperties` can fail to compile on paste.
import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type CSSProperties,
  type ReactNode,
} from "react";

// ===== BEGIN GENERATED ENGINE — do not edit by hand =====
// Generated by scripts/generateFramerEngine.ts — do not edit by hand.
// Run `npm run generate:framer` after changing any of:
//   src/puzzleIndex.ts
//   src/guessChecker.ts
//   src/bonusRound.ts
//   src/shareCard.ts
//   src/stats.ts
//   src/gameState.ts
// `npm test` and CI both fail when this block drifts from src/.

// --- from src/puzzleIndex.ts ---

const MS_PER_DAY = 24 * 60 * 60 * 1000;

function utcDayNumber(date: Date): number {
  const utcMidnight = Date.UTC(
    date.getUTCFullYear(),
    date.getUTCMonth(),
    date.getUTCDate()
  );
  return Math.floor(utcMidnight / MS_PER_DAY);
}

function getDaysSinceLaunch(today: Date, launchDate: Date): number {
  return utcDayNumber(today) - utcDayNumber(launchDate);
}

function getTodayPuzzleIndex(
  today: Date,
  launchDate: Date,
  listLength: number
): number {
  if (listLength <= 0) {
    throw new Error("listLength must be greater than 0");
  }
  const daysSinceLaunch = getDaysSinceLaunch(today, launchDate);
  return ((daysSinceLaunch % listLength) + listLength) % listLength;
}

/**
 * Milliseconds until the next puzzle. Puzzles roll over at UTC midnight —
 * `getTodayPuzzleIndex` counts UTC days — so this must work off UTC and not
 * the visitor's local midnight, or the countdown would be wrong by the
 * viewer's timezone offset.
 *
 * At exactly midnight this returns a full day rather than zero: the puzzle
 * that just appeared is today's, and the next one is 24 hours out.
 */
function msUntilNextUtcMidnight(now: Date): number {
  // Day + 1 overflows correctly into the next month or year; Date.UTC
  // normalises it.
  const nextMidnight = Date.UTC(
    now.getUTCFullYear(),
    now.getUTCMonth(),
    now.getUTCDate() + 1
  );
  return nextMidnight - now.getTime();
}

/** A duration as `HH:MM:SS`, floored to the second and never negative. */
function formatCountdown(milliseconds: number): string {
  const totalSeconds = Math.max(0, Math.floor(milliseconds / 1000));
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;
  const pad = (value: number) => String(value).padStart(2, "0");
  return `${pad(hours)}:${pad(minutes)}:${pad(seconds)}`;
}

// --- from src/guessChecker.ts ---

function normalizeGuess(input: string): string {
  return input
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s]/g, "")
    .replace(/\s+/g, " ");
}

function stripTrailingS(word: string): string {
  return word.endsWith("s") && word.length > 3 ? word.slice(0, -1) : word;
}

function levenshteinDistance(a: string, b: string): number {
  const rows = a.length + 1;
  const cols = b.length + 1;
  const matrix: number[][] = Array.from({ length: rows }, () =>
    new Array(cols).fill(0)
  );

  for (let i = 0; i < rows; i++) matrix[i][0] = i;
  for (let j = 0; j < cols; j++) matrix[0][j] = j;

  for (let i = 1; i < rows; i++) {
    for (let j = 1; j < cols; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      matrix[i][j] = Math.min(
        matrix[i - 1][j] + 1,
        matrix[i][j - 1] + 1,
        matrix[i - 1][j - 1] + cost
      );
    }
  }

  return matrix[rows - 1][cols - 1];
}

function fuzzyTolerance(word: string): number {
  if (word.length <= 4) return 0;
  if (word.length <= 7) return 1;
  return 2;
}

function namesMatch(guess: string, candidate: string): boolean {
  const normalizedGuess = stripTrailingS(normalizeGuess(guess));
  const normalizedCandidate = stripTrailingS(normalizeGuess(candidate));

  if (normalizedGuess === normalizedCandidate) return true;

  const tolerance = fuzzyTolerance(normalizedCandidate);

  // Levenshtein distance is never smaller than the difference in lengths, so a
  // length gap wider than the tolerance cannot possibly match. Checking that
  // first is exact — it changes no result — and it keeps the O(n*m) matrix
  // below from being allocated for input that could never match: without it, a
  // pasted megabyte allocates millions of cells per candidate and freezes the
  // tab.
  if (
    Math.abs(normalizedGuess.length - normalizedCandidate.length) > tolerance
  ) {
    return false;
  }

  return levenshteinDistance(normalizedGuess, normalizedCandidate) <= tolerance;
}

function checkGuess(
  guess: string,
  commonName: string,
  aliases: string[]
): boolean {
  const candidates = [commonName, ...aliases];
  return candidates.some((candidate) => namesMatch(guess, candidate));
}

// --- from src/bonusRound.ts ---

interface ShuffledBonus {
  options: string[];
  answerIndex: number;
}

/**
 * mulberry32 — a small deterministic PRNG. Math.random cannot be used: every
 * player must see the same option order on the same day, or two people
 * comparing results are not talking about the same thing.
 */
function seededRandom(seed: number): () => number {
  let state = seed >>> 0;
  return function next(): number {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * Fisher-Yates over a copy, seeded by the puzzle number.
 *
 * Relies on options being distinct — `validateAnimalData` enforces that — so
 * `indexOf` finds the answer's new position unambiguously.
 */
function shuffleBonusOptions(
  options: string[],
  answerIndex: number,
  seed: number
): ShuffledBonus {
  const answer = options[answerIndex];
  const shuffled = [...options];
  const random = seededRandom(seed);

  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    const swap = shuffled[i];
    shuffled[i] = shuffled[j];
    shuffled[j] = swap;
  }

  return { options: shuffled, answerIndex: shuffled.indexOf(answer) };
}

// --- from src/shareCard.ts ---

function buildShareText(
  puzzleNumber: number,
  animalEmoji: string,
  guessesUsed: number | null,
  siteUrl?: string,
  bonus?: "hit" | "miss"
): string {
  const result = guessesUsed === null ? "X/3" : `${guessesUsed}/3`;

  // Misses are shown, not hidden. A bare score on a bonus day would be
  // ambiguous — no round today, or one they failed? — and the comparison
  // between a friend's ⭐ and your ⬜ is the thing that drives a click.
  const bonusMark = bonus === "hit" ? " ⭐" : bonus === "miss" ? " ⬜" : "";

  const scoreLine = `WhichAnimalToday #${puzzleNumber} ${animalEmoji} ${result}${bonusMark}`;

  // The URL is what makes a shared result findable — without it a recipient
  // has a score and no way to reach the game. Optional so the pre-launch
  // state (constant present but not yet set) doesn't append a blank line.
  const trimmedUrl = siteUrl?.trim();
  return trimmedUrl ? `${scoreLine}\n${trimmedUrl}` : scoreLine;
}

// --- from src/stats.ts ---

interface Stats {
  played: number;
  wins: number;
  /** Integer 0-100. 0 when nothing has been played. */
  winPercent: number;
  currentStreak: number;
  maxStreak: number;
  /** Wins on guess 1, 2, and 3 respectively. */
  distribution: [number, number, number];
  /** Days that offered a bonus round and were played. */
  bonusRounds: number;
  /** Of those, the ones the player got right. */
  bonusHits: number;
}

/** Whole days since the epoch for a YYYY-MM-DD UTC date string. */
function dayNumber(date: string): number {
  return Math.floor(new Date(`${date}T00:00:00Z`).getTime() / MS_PER_DAY);
}

function computeStats(history: DailyResult[], today: string): Stats {
  const sorted = [...history].sort((a, b) => a.date.localeCompare(b.date));

  const played = sorted.length;
  const wins = sorted.filter((entry) => entry.solved).length;
  const winPercent = played === 0 ? 0 : Math.round((wins / played) * 100);

  const distribution: [number, number, number] = [0, 0, 0];
  for (const entry of sorted) {
    if (entry.solved && entry.guessesUsed >= 1 && entry.guessesUsed <= 3) {
      distribution[entry.guessesUsed - 1] += 1;
    }
  }

  // Walk the history once, tracking the run of solved entries on
  // consecutive calendar days. `run` ends up holding the streak that
  // terminates at the most recent entry.
  let maxStreak = 0;
  let run = 0;
  let previous: DailyResult | null = null;
  for (const entry of sorted) {
    if (!entry.solved) {
      run = 0;
    } else if (
      previous !== null &&
      previous.solved &&
      dayNumber(entry.date) - dayNumber(previous.date) === 1
    ) {
      run += 1;
    } else {
      run = 1;
    }
    if (run > maxStreak) maxStreak = run;
    previous = entry;
  }

  // A streak is only alive if the player has actually shown up recently.
  // Nothing is written on days they don't play, so absence has to be
  // detected by comparing against today rather than by a stored counter.
  let currentStreak = 0;
  const last = played === 0 ? null : sorted[played - 1];
  if (last !== null && last.solved) {
    const gap = dayNumber(today) - dayNumber(last.date);
    if (gap === 0 || gap === 1) currentStreak = run;
  }

  // Only the two known values count, so a hand-edited storage value can
  // neither inflate the tally nor throw.
  let bonusRounds = 0;
  let bonusHits = 0;
  for (const entry of sorted) {
    if (entry.bonus === "hit") {
      bonusRounds += 1;
      bonusHits += 1;
    } else if (entry.bonus === "miss") {
      bonusRounds += 1;
    }
  }

  return {
    played,
    wins,
    winPercent,
    currentStreak,
    maxStreak,
    distribution,
    bonusRounds,
    bonusHits,
  };
}

// --- from src/gameState.ts ---

interface StorageLike {
  getItem(key: string): string | null;
  setItem(key: string, value: string): void;
}

interface DailyResult {
  date: string;
  puzzleNumber: number;
  solved: boolean;
  guessesUsed: number;
  /**
   * Absent when the day offered no bonus round. Deliberately does NOT bump
   * SCHEMA_VERSION: `loadState` maps an unrecognised version to an empty
   * history, so a bump would wipe every existing player's stats. An optional
   * field is read correctly by the v2 loader, and a pre-bonus entry having no
   * value here is accurate rather than missing.
   */
  bonus?: "hit" | "miss";
}

const SCHEMA_VERSION = 2;

const STORAGE_KEY = "whichanimaltoday_state";

interface StoredStateV2 {
  version: 2;
  history: DailyResult[];
}

/** The pre-2026-07-29 shape, read only during migration. */
interface StoredStateV1 {
  lastResult: DailyResult | null;
  currentStreak: number;
}

function emptyState(): StoredStateV2 {
  return { version: SCHEMA_VERSION, history: [] };
}

/**
 * A malformed entry (e.g. `null`, or missing/mistyped fields) would
 * otherwise pass the `Array.isArray` check below and then throw later
 * inside `computeStats` (`a.date.localeCompare`) — which, in the Framer
 * component, gets swallowed by the fetch `.catch` and bricks the game on
 * every load thereafter, since nothing ever clears the bad stored value.
 * Filtering here lets a corrupt value self-heal instead.
 */
function isWellFormedEntry(entry: unknown): entry is DailyResult {
  if (typeof entry !== "object" || entry === null) return false;
  const candidate = entry as Partial<DailyResult>;
  return (
    typeof candidate.date === "string" &&
    typeof candidate.solved === "boolean" &&
    typeof candidate.guessesUsed === "number"
  );
}

function loadState(storage: StorageLike): StoredStateV2 {
  let raw: string | null;
  try {
    raw = storage.getItem(STORAGE_KEY);
  } catch {
    // Storage can throw outright rather than return null: blocked cookies
    // and Safari private mode make even reading a SecurityError. Degrade to
    // an empty history so every stat reads zero.
    return emptyState();
  }
  if (!raw) return emptyState();

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return emptyState();
  }
  if (typeof parsed !== "object" || parsed === null) return emptyState();

  const candidate = parsed as Partial<StoredStateV2> & Partial<StoredStateV1>;

  if (candidate.version === SCHEMA_VERSION) {
    return Array.isArray(candidate.history)
      ? {
          version: SCHEMA_VERSION,
          history: candidate.history.filter(isWellFormedEntry),
        }
      : emptyState();
  }

  // v1 -> v2. `currentStreak` is deliberately dropped: the number is known
  // but the days that produced it are not, so it cannot become real
  // history. See spec §2 "Accepted loss".
  if ("lastResult" in candidate) {
    const last = candidate.lastResult;
    return { version: SCHEMA_VERSION, history: last ? [last] : [] };
  }

  return emptyState();
}

function saveState(storage: StorageLike, state: StoredStateV2): void {
  try {
    storage.setItem(STORAGE_KEY, JSON.stringify(state));
  } catch {
    // Quota exceeded, or storage blocked entirely. Nothing to recover: the
    // player gets a fresh game on each load and their stats stay at zero.
    // Throwing here would crash the game the moment they finish a puzzle.
  }
}

function getHistory(storage: StorageLike): DailyResult[] {
  return loadState(storage).history;
}

function getLastResult(storage: StorageLike): DailyResult | null {
  const history = loadState(storage).history;
  if (history.length === 0) return null;
  const sorted = [...history].sort((a, b) => a.date.localeCompare(b.date));
  return sorted[sorted.length - 1];
}

function getCurrentStreak(
  storage: StorageLike,
  today: string
): number {
  return computeStats(loadState(storage).history, today).currentStreak;
}

function getStats(storage: StorageLike, today: string): Stats {
  return computeStats(loadState(storage).history, today);
}

function recordResult(
  storage: StorageLike,
  result: DailyResult
): number {
  // Idempotent by date: re-recording the same day replaces that entry
  // rather than appending, so a double-fire can't inflate `played`.
  const history = loadState(storage).history.filter(
    (entry) => entry.date !== result.date
  );
  history.push(result);
  history.sort((a, b) => a.date.localeCompare(b.date));

  saveState(storage, { version: SCHEMA_VERSION, history });

  // The result being recorded is by definition today's.
  return computeStats(history, result.date).currentStreak;
}

function hasPlayedToday(
  storage: StorageLike,
  today: string
): boolean {
  return loadState(storage).history.some((entry) => entry.date === today);
}

// ===== END GENERATED ENGINE =====

// ---------- Component-local types and helpers (not generated) ----------

// `BonusRound` is redeclared here rather than generated: src/animalData.ts is
// not in ENGINE_MODULE_PATHS because the component never needs
// `validateAnimalData` at runtime.
interface BonusRound {
  question: string;
  options: string[];
  answerIndex: number;
}

interface Animal {
  commonName: string;
  aliases: string[];
  imageUrl: string;
  hint1: string;
  hint2: string;
  hint3: string;
  funFacts: string;
  category: string;
  imageAttribution: string;
  species?: string;
  bonus?: BonusRound;
}

// Rough category → emoji lookup for the share card. Not stored per-animal
// (the data model doesn't have an emoji field) — this is a light touch,
// not meant to spoil the specific species.
const CATEGORY_EMOJI: Record<string, string> = {
  mammal: "🐾",
  bird: "🐦",
  fish: "🐟",
  reptile: "🦎",
  amphibian: "🐸",
  insect: "🐛",
  marine: "🐠",
};

function todayDateString(): string {
  return new Date().toISOString().slice(0, 10);
}

const EMPTY_STATS: Stats = {
  played: 0,
  wins: 0,
  winPercent: 0,
  currentStreak: 0,
  maxStreak: 0,
  distribution: [0, 0, 0],
  bonusRounds: 0,
  bonusHits: 0,
};

// The generated engine takes a StorageLike so it can be unit-tested against
// a fake. In the browser that is window.localStorage — but the property
// access itself throws when cookies are blocked, and the object does not
// exist during SSR, so both are guarded here rather than inside the engine.
const browserStorage: StorageLike = {
  getItem(key) {
    if (typeof window === "undefined") return null;
    try {
      return window.localStorage.getItem(key);
    } catch {
      return null;
    }
  },
  setItem(key, value) {
    if (typeof window === "undefined") return;
    try {
      window.localStorage.setItem(key, value);
    } catch {
      // Quota exceeded, or storage blocked entirely. The game continues; the
      // result just will not survive a reload.
    }
  },
};

// ---------- Component ----------

function Modal({
  title,
  open,
  footer,
  onClose,
  children,
}: {
  title: string;
  open: boolean;
  footer?: string;
  onClose: () => void;
  children: ReactNode;
}) {
  const cardRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (!open) return;

    // Remember what had focus before the panel opened, so it can be
    // restored on close — otherwise focus falls to <body> when this
    // panel's contents unmount, and a keyboard user loses their place.
    const previouslyFocused = document.activeElement as HTMLElement | null;

    // Move focus into the panel so keyboard and screen-reader users land
    // here rather than continuing through the page behind it.
    cardRef.current?.focus();

    function onKeyDown(event: KeyboardEvent) {
      if (event.key === "Escape") onClose();
    }
    window.addEventListener("keydown", onKeyDown);
    return () => {
      window.removeEventListener("keydown", onKeyDown);
      // Guard against the trigger having been removed from the DOM or no
      // longer being focusable in the meantime.
      if (
        previouslyFocused &&
        typeof previouslyFocused.focus === "function" &&
        document.body.contains(previouslyFocused)
      ) {
        previouslyFocused.focus();
      }
    };
  }, [open, onClose]);

  if (!open) return null;

  return (
    <div
      style={styles.modalBackdrop}
      onClick={(event) => {
        // Only a click that genuinely originated on the backdrop itself
        // should close the panel. Without this check, drag-selecting the
        // share postcard's `userSelect: "all"` text and releasing the
        // mouse outside the card fires a click on the backdrop (the click
        // target follows mouseup, not mousedown) and dismisses the panel
        // mid-copy.
        if (event.target === event.currentTarget) onClose();
      }}
      data-testid="modal-backdrop"
    >
      <div
        ref={cardRef}
        role="dialog"
        aria-modal="true"
        aria-label={title}
        tabIndex={-1}
        style={styles.modalCard}
        onClick={(event) => event.stopPropagation()}
      >
        <div style={styles.modalHeader}>
          <div style={styles.modalTitle}>{title}</div>
          <button
            type="button"
            aria-label="Close"
            style={styles.modalClose}
            onClick={onClose}
          >
            ✕
          </button>
        </div>
        <div style={styles.modalBody}>{children}</div>
        {footer && <div style={styles.modalFooter}>{footer}</div>}
      </div>
    </div>
  );
}

function StatsPanel({
  stats,
  todayGuesses,
}: {
  stats: Stats;
  todayGuesses: number | null;
}) {
  if (stats.played === 0) {
    return <div style={styles.statsEmpty}>No specimens identified yet.</div>;
  }

  const largest = Math.max(...stats.distribution);

  return (
    <>
      <div style={styles.statsRow}>
        {[
          { label: "Played", value: stats.played },
          { label: "Win %", value: stats.winPercent },
          { label: "Current", value: stats.currentStreak },
          { label: "Max", value: stats.maxStreak },
        ].map((figure) => (
          <div key={figure.label} style={styles.statsFigure}>
            <div style={styles.statsValue}>{figure.value}</div>
            <div style={styles.statsLabel}>{figure.label}</div>
          </div>
        ))}
      </div>

      <div style={styles.distTitle}>Guess distribution</div>
      {stats.distribution.map((count, index) => {
        const guessNumber = index + 1;
        // When every game has been lost, `largest` is 0 and a
        // proportional width would divide by zero — fall back to a fixed
        // minimum so the bars still render.
        const width = largest === 0 ? 6 : Math.max(6, (count / largest) * 100);
        const highlighted = todayGuesses === guessNumber;
        return (
          <div key={guessNumber} style={styles.distRow}>
            <span style={styles.distIndex}>{guessNumber}</span>
            <span
              style={{
                ...styles.distBar,
                width: `${width}%`,
                background: highlighted ? tokens.coral : tokens.moss,
              }}
            />
            <span style={styles.distCount}>{count}</span>
          </div>
        );
      })}

      {stats.bonusRounds > 0 && (
        <div style={styles.bonusTally}>
          Bonus rounds {stats.bonusHits}/{stats.bonusRounds}
        </div>
      )}
    </>
  );
}

type GamePhase = "loading" | "error" | "playing" | "bonus" | "done";

export default function GameComponent() {
  const [phase, setPhase] = useState<GamePhase>("loading");
  const [animal, setAnimal] = useState<Animal | null>(null);
  const [puzzleNumber, setPuzzleNumber] = useState(0);
  const [guessesLeft, setGuessesLeft] = useState(3);
  const [hintsRevealed, setHintsRevealed] = useState(0);
  const [guessInput, setGuessInput] = useState("");
  const [solved, setSolved] = useState(false);
  const [stats, setStats] = useState<Stats>(EMPTY_STATS);
  const [message, setMessage] = useState<string | null>(null);
  const [shareCopied, setShareCopied] = useState(false);
  const [bonusResult, setBonusResult] = useState<"hit" | "miss" | null>(null);
  const [bonusPick, setBonusPick] = useState<number | null>(null);
  // The guess count is known when the bonus round opens but is not written to
  // storage until the round finishes, so it has to be held across the phase.
  const [pendingGuessesUsed, setPendingGuessesUsed] = useState(0);
  // A bonus flow writes to storage twice — once when the round opens, once
  // when it ends. Both writes must land on the SAME date or `recordResult`'s
  // date filter cannot collapse them, and a round left open across UTC
  // midnight would leave a second entry misdated to the new day. Pin the
  // date at the first write and reuse it for the second.
  const [pendingDate, setPendingDate] = useState("");
  // Immediate colour feedback on a guess: null most of the time, "hit" or
  // "miss" for a beat after the player commits.
  const [guessFlash, setGuessFlash] = useState<"hit" | "miss" | null>(null);
  // A correct guess jumps to the reveal, which unmounts the input — so the
  // green flash would never be seen unless the transition is held. The handle
  // lives in a ref and is cleared on unmount, so a player who navigates away
  // mid-flash never has a timer fire against an unmounted component.
  const flashTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(
    () => () => {
      if (flashTimer.current) clearTimeout(flashTimer.current);
    },
    []
  );
  const [openPanel, setOpenPanel] = useState<"stats" | "howto" | null>(null);
  const [countdown, setCountdown] = useState(() =>
    formatCountdown(msUntilNextUtcMidnight(new Date()))
  );

  const closePanel = useCallback(() => setOpenPanel(null), []);

  // Stats come from localStorage alone and have nothing to do with the
  // network — read them on mount independent of the animals fetch below,
  // so the Statistics panel reflects the player's real history even while
  // that fetch is slow, rejects, or 404s. See fix 2 of the branch review.
  useEffect(() => {
    setStats(getStats(browserStorage, todayDateString()));
  }, []);

  // Only ticks while the reveal card is on screen — that is the only place
  // the clock is rendered, and a finished player is exactly who the "come
  // back tomorrow" nudge is for. The interval is cleared on unmount and
  // whenever the phase changes, so it never outlives the view.
  useEffect(() => {
    if (phase !== "done") return;

    function tick() {
      setCountdown(formatCountdown(msUntilNextUtcMidnight(new Date())));
    }

    tick(); // paint immediately rather than after the first second
    const timer = setInterval(tick, 1000);
    return () => clearInterval(timer);
  }, [phase]);

  const shuffledBonus = useMemo<ShuffledBonus | null>(() => {
    if (!animal?.bonus) return null;

    // `animal` came off the wire: data/animals.json is fetched at runtime from
    // a file a content pipeline writes, so the component cannot assume anyone
    // validated it. A malformed `bonus` reaching `shuffleBonusOptions` throws
    // during render, inside this memo — where the fetch's `.catch()` cannot
    // reach it — and takes the whole day's puzzle down, not just the bonus
    // round. Degrade to `null`, which is already the well-handled "this animal
    // has no bonus round" case, and the rest of the component needs no change.
    const { options, answerIndex } = animal.bonus;
    if (!Array.isArray(options) || options.length !== 4) return null;
    if (
      !Number.isInteger(answerIndex) ||
      answerIndex < 0 ||
      answerIndex >= options.length
    ) {
      return null;
    }

    return shuffleBonusOptions(options, answerIndex, puzzleNumber);
  }, [animal, puzzleNumber]);

  useEffect(() => {
    let cancelled = false;

    fetch(ANIMALS_JSON_URL)
      .then((res) => {
        if (!res.ok) throw new Error(`Fetch failed: ${res.status}`);
        return res.json();
      })
      .then((animals: Animal[]) => {
        if (cancelled) return;
        if (!Array.isArray(animals) || animals.length === 0) {
          throw new Error("Animal list is empty");
        }

        const today = new Date();
        const index = getTodayPuzzleIndex(today, LAUNCH_DATE, animals.length);
        const todaysAnimal = animals[index];
        const daysSinceLaunch = getDaysSinceLaunch(today, LAUNCH_DATE);
        const puzzleNum = daysSinceLaunch + 1;

        setAnimal(todaysAnimal);
        setPuzzleNumber(puzzleNum);

        const history = getHistory(browserStorage);
        const today8601 = todayDateString();

        const todayEntry = history.find((entry) => entry.date === today8601);
        if (todayEntry) {
          setSolved(todayEntry.solved);
          setBonusResult(todayEntry.bonus ?? null);
          setGuessesLeft(3 - todayEntry.guessesUsed);
          setHintsRevealed(Math.min(todayEntry.guessesUsed, 3));
          setPhase("done");
        } else {
          setPhase("playing");
        }
      })
      .catch(() => {
        if (!cancelled) setPhase("error");
      });

    return () => {
      cancelled = true;
    };
  }, []);

  function submitGuess() {
    if (!animal || guessesLeft <= 0) return;
    const trimmed = guessInput.trim();
    if (!trimmed) return;

    const correct = checkGuess(trimmed, animal.commonName, animal.aliases);
    const guessesUsedSoFar = 3 - guessesLeft;
    const newGuessesUsed = guessesUsedSoFar + 1;
    const newHintsRevealed = Math.min(newGuessesUsed, 3);

    setHintsRevealed(newHintsRevealed);
    setGuessInput("");

    if (correct) {
      setGuessFlash("hit");
      setMessage("✓ Correct!");
      if (flashTimer.current) clearTimeout(flashTimer.current);
      flashTimer.current = setTimeout(() => {
        setGuessFlash(null);
        advanceAfterCorrectGuess(newGuessesUsed);
      }, 900);
      return;
    }

    if (newGuessesUsed >= 3) {
      finishGame(false, newGuessesUsed, null);
      return;
    }

    setGuessesLeft(3 - newGuessesUsed);
    setGuessFlash("miss");
    if (flashTimer.current) clearTimeout(flashTimer.current);
    flashTimer.current = setTimeout(() => setGuessFlash(null), 1400);
    setMessage("✗ Not quite — here's another clue.");
  }

  /**
   * The win path, split out of `submitGuess` so the green flash can be shown
   * before it runs. Behaviour is unchanged from when it was inline.
   */
  function advanceAfterCorrectGuess(newGuessesUsed: number) {
    if (!animal) return;

      // The bonus is offered only on a win — a player who used all three
      // guesses is already being handed the answer on the reveal card.
      // Gate on `shuffledBonus`, not on `animal.bonus`: the memo returns null
      // for a malformed bonus, and entering the phase without a round to
      // render would strand the player on an empty card.
      if (shuffledBonus) {
        // Bank the win NOW, before the bonus round opens, with no `bonus`
        // field. Solving stage one IS the win; the bonus must never be able
        // to cost it. A player who closes the tab, navigates away, or
        // refreshes mid-round has already earned this day and keeps their
        // streak — they simply read as "solved, no bonus round completed",
        // which is exactly what happened. `finishGame` re-records the same
        // date when the round ends: `recordResult` is idempotent by date
        // (it filters `entry.date !== result.date` before pushing), so the
        // second write updates this entry in place rather than adding one.
        const today = todayDateString();
        recordResult(browserStorage, {
          date: today,
          puzzleNumber,
          solved: true,
          guessesUsed: newGuessesUsed,
        });
        // Keep the in-memory figures in step with what storage now holds, so
        // the header streak badge and the Statistics panel are correct while
        // the round is open. `bonusRounds`/`bonusHits` still read the prior
        // days only, which is accurate — this round has not been answered.
        setStats(getStats(browserStorage, today));
        setSolved(true);
        setGuessesLeft(3 - newGuessesUsed);
        setPendingGuessesUsed(newGuessesUsed);
        setPendingDate(today);
        setMessage(null);
        setPhase("bonus");
      } else {
        finishGame(true, newGuessesUsed, null);
      }
  }

  function finishGame(
    didSolve: boolean,
    guessesUsed: number,
    bonus: "hit" | "miss" | null
  ) {
    // A non-null `bonus` means this is the second write of a bonus flow, and
    // only that flow spans two writes — so only it reuses the date pinned
    // when the round opened. Every other path (the no-bonus win, the loss)
    // passes null and computes the date fresh at completion time, exactly as
    // before. Without this, a round left open across UTC midnight would write
    // its second entry under the new day, leaving two entries instead of one.
    // The `||` is belt-and-braces: `bonus` is only ever non-null from the
    // reveal button, which is reachable only from a phase that set
    // `pendingDate` first, so the fallback should be unreachable.
    const today =
      bonus !== null ? pendingDate || todayDateString() : todayDateString();
    // src/'s recordResult returns just the streak number; the stats panel
    // needs every figure, so read the full set back rather than diverging
    // from the generated signature. With storage blocked this reads zeros —
    // see the codegen design doc's "Accepted behavioural change".
    recordResult(browserStorage, {
      date: today,
      puzzleNumber,
      solved: didSolve,
      guessesUsed,
      ...(bonus ? { bonus } : {}),
    });
    setBonusResult(bonus);
    setSolved(didSolve);
    setGuessesLeft(3 - guessesUsed);
    setStats(getStats(browserStorage, today));
    setMessage(null);
    setPhase("done");
  }

  function pickBonus(index: number) {
    // One shot: once a pick lands it is locked, and a second click does
    // nothing. There is deliberately no confirm step — the moment of
    // commitment is the whole mechanic.
    if (bonusPick !== null || !shuffledBonus) return;
    setBonusPick(index);
  }

  function getShareText(): string {
    if (!animal) return "";
    const emoji = CATEGORY_EMOJI[animal.category.toLowerCase()] ?? "🐾";
    return buildShareText(
      puzzleNumber,
      emoji,
      solved ? 3 - guessesLeft : null,
      SITE_URL,
      bonusResult ?? undefined
    );
  }

  function copyShareText() {
    const text = getShareText();
    if (!text) return;

    const markCopied = () => {
      setShareCopied(true);
      setTimeout(() => setShareCopied(false), 2000);
    };

    if (typeof navigator !== "undefined" && navigator.clipboard) {
      navigator.clipboard.writeText(text).then(markCopied, () => {
        // Clipboard write can fail silently (permissions, unfocused
        // document, older browsers) — the visible share-text box below
        // the button is the fallback so the user always has something
        // to select and copy by hand, never a dead button.
        setShareCopied(false);
      });
    }
  }

  const hints = animal ? [animal.hint1, animal.hint2, animal.hint3] : [];

  // `puzzleNumber` defaults to 0 until the animals fetch resolves. Now that
  // stats load independently of that fetch, a player can open a panel
  // before it does — omit the footer rather than showing a meaningless
  // "FIELD FILE #0".
  const fieldFileFooter =
    puzzleNumber > 0 ? `FIELD FILE #${puzzleNumber}` : undefined;

  return (
    <div style={styles.page}>
      <style>{css}</style>

      <header style={styles.header}>
        <div>
          <div style={styles.wordmark}>WhichAnimalToday</div>
          <div style={styles.tagline}>a new specimen every day</div>
        </div>
        <div style={styles.headerControls}>
          {stats.currentStreak > 0 && (
            <div style={styles.streakBadge}>
              🔥 {stats.currentStreak} day{stats.currentStreak === 1 ? "" : "s"}
            </div>
          )}
          <button
            type="button"
            aria-label="Statistics"
            style={styles.iconTab}
            onClick={() => setOpenPanel("stats")}
          >
            <span aria-hidden="true">📊</span>
          </button>
          <button
            type="button"
            aria-label="How to play"
            style={styles.iconTab}
            onClick={() => setOpenPanel("howto")}
          >
            <span aria-hidden="true">❓</span>
          </button>
          <a
            href="/archive"
            style={styles.archivePill}
            aria-label="Open your field journal"
          >
            <span aria-hidden="true">📔</span> Field Journal →
          </a>
        </div>
      </header>

      <Modal
        title="Statistics"
        open={openPanel === "stats"}
        footer={fieldFileFooter}
        onClose={closePanel}
      >
        <StatsPanel
          stats={stats}
          todayGuesses={phase === "done" && solved ? 3 - guessesLeft : null}
        />
        {phase === "done" && (
          <>
            <div style={styles.postcard}>
              <div style={styles.postcardText}>{getShareText()}</div>
              <div style={styles.postcardHint}>tap to select and copy by hand</div>
            </div>
            <button style={styles.shareButton} onClick={copyShareText}>
              {shareCopied ? "Copied!" : "Copy result"}
            </button>
          </>
        )}
      </Modal>

      <Modal
        title="How to Play"
        open={openPanel === "howto"}
        footer={fieldFileFooter}
        onClose={closePanel}
      >
        {HOW_TO_PLAY.map((section) => (
          <div key={section.heading} style={styles.howtoSection}>
            <span style={styles.howtoHeading}>{section.heading}</span>{" "}
            <span style={styles.howtoBody}>{section.body}</span>
          </div>
        ))}
        <a href="/archive" style={styles.howtoLink}>
          Browse the Archive →
        </a>
      </Modal>

      {phase === "loading" && <div style={styles.statusText}>Loading today's specimen…</div>}

      {phase === "error" && (
        <div style={styles.statusText}>
          Couldn't load today's animal. Please refresh the page.
        </div>
      )}

      {animal && phase !== "loading" && phase !== "error" && (
        <>
          <div style={styles.photoFrame}>
            <div style={styles.tapeCorner} />
            <img
              src={animal.imageUrl}
              alt="Today's mystery animal"
              style={{
                ...styles.photo,
                filter: phase === "done" ? "none" : "none",
              }}
            />
            {phase === "done" && (
              <div style={styles.stamp}>{solved ? "IDENTIFIED" : "REVEALED"}</div>
            )}
          </div>
          <div style={styles.fileTag}>FIELD FILE #{puzzleNumber}</div>

          {phase === "playing" && (
            <>
              <div style={styles.dots}>
                {[0, 1, 2].map((i) => (
                  <span
                    key={i}
                    style={{
                      ...styles.dot,
                      opacity: i < guessesLeft ? 1 : 0.25,
                    }}
                  />
                ))}
                <span style={styles.dotsLabel}>{guessesLeft} guesses left</span>
              </div>

              <div style={styles.guessRow}>
                <input
                  style={{
                    ...styles.input,
                    borderBottomStyle: guessFlash ? "solid" : "dashed",
                    borderBottomColor:
                      guessFlash === "hit"
                        ? tokens.moss
                        : guessFlash === "miss"
                          ? tokens.coral
                          : tokens.line,
                    background:
                      guessFlash === "hit"
                        ? "rgba(90,122,79,0.12)"
                        : guessFlash === "miss"
                          ? "rgba(198,93,59,0.12)"
                          : "transparent",
                  }}
                  type="text"
                  placeholder="what animal is this?"
                  // Generous for any real animal name — the longest plausible
                  // guess is a scientific binomial well under this. Defence in
                  // depth only: namesMatch rejects over-long input on its own,
                  // since an attribute like this is trivially bypassed.
                  maxLength={80}
                  value={guessInput}
                  onChange={(e) => setGuessInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter") submitGuess();
                  }}
                />
                <button style={styles.guessButton} onClick={submitGuess}>
                  Guess →
                </button>
              </div>

              {message && (
                <div
                  style={{
                    ...styles.message,
                    color:
                      guessFlash === "hit"
                        ? tokens.moss
                        : guessFlash === "miss"
                          ? tokens.coral
                          : styles.message.color,
                  }}
                >
                  {message}
                </div>
              )}

              {hintsRevealed > 0 && (
                <div style={styles.clues}>
                  <div style={styles.cluesLabel}>── clues ──</div>
                  {hints.slice(0, hintsRevealed).map((hint, i) => (
                    <div key={i} style={styles.clueCard}>
                      <span style={styles.cluePin}>📎</span>
                      <span style={styles.clueLabel}>Clue {i + 1}</span>
                      <span style={styles.clueText}>{hint}</span>
                    </div>
                  ))}
                </div>
              )}
            </>
          )}

          {phase === "bonus" && animal.bonus && shuffledBonus && (
            <div style={styles.bonusCard}>
              <div style={styles.bonusLabel}>── bonus round ──</div>
              <div style={styles.bonusQuestion}>{animal.bonus.question}</div>

              <div style={styles.bonusOptions}>
                {shuffledBonus.options.map((option, index) => {
                  const picked = bonusPick === index;
                  const isAnswer = index === shuffledBonus.answerIndex;
                  const settled = bonusPick !== null;
                  // After a pick, the right answer is always shown — a player
                  // who guessed wrong still learns the species.
                  const background = !settled
                    ? tokens.paper
                    : isAnswer
                      ? tokens.moss
                      : picked
                        ? tokens.coral
                        : tokens.paper;
                  // Colour alone cannot carry the outcome (WCAG 1.4.1), and
                  // this is the payoff moment of the whole feature. A glyph
                  // rides alongside the fill for sighted players, and the
                  // aria-label states the outcome in words for everyone else.
                  const marker = !settled
                    ? ""
                    : isAnswer
                      ? " ✓ Correct"
                      : picked
                        ? " ✗ Wrong"
                        : "";
                  const outcomeLabel = !settled
                    ? undefined
                    : isAnswer
                      ? picked
                        ? `${option} — your pick, correct answer`
                        : `${option} — correct answer`
                      : picked
                        ? `${option} — your pick, incorrect`
                        : `${option} — not picked`;
                  return (
                    <button
                      key={option}
                      style={{
                        ...styles.bonusOption,
                        background,
                        cursor: settled ? "default" : "pointer",
                      }}
                      // aria-disabled rather than disabled: a disabled button
                      // leaves the accessibility tree, so a screen-reader user
                      // could not read back the result they just earned, and
                      // the browser greys the text. `pickBonus` returns early
                      // once `bonusPick` is set, so the one-shot lock does not
                      // depend on the attribute.
                      aria-disabled={settled}
                      aria-label={outcomeLabel}
                      onClick={() => pickBonus(index)}
                    >
                      {option}
                      {marker}
                    </button>
                  );
                })}
              </div>

              {bonusPick !== null && (
                <div
                  style={{
                    ...styles.bonusResult,
                    color:
                      bonusPick === shuffledBonus.answerIndex
                        ? tokens.moss
                        : tokens.coral,
                  }}
                >
                  {bonusPick === shuffledBonus.answerIndex
                    ? `✓ Correct — it's the ${shuffledBonus.options[shuffledBonus.answerIndex]}`
                    : `✗ Not that one — it's the ${shuffledBonus.options[shuffledBonus.answerIndex]}`}
                </div>
              )}

              {bonusPick !== null && (
                <button
                  style={styles.guessButton}
                  onClick={() =>
                    finishGame(
                      true,
                      pendingGuessesUsed,
                      bonusPick === shuffledBonus.answerIndex ? "hit" : "miss"
                    )
                  }
                >
                  See the reveal →
                </button>
              )}
            </div>
          )}

          {phase === "done" && (
            <div style={styles.revealCard}>
              <div style={styles.revealName}>{animal.commonName}</div>
              {animal.species && (
                <div style={styles.revealSpecies}>
                  specifically, a {animal.species}
                </div>
              )}
              {bonusResult && (
                <div style={styles.revealBonus}>
                  {bonusResult === "hit"
                    ? "⭐ Bonus round — you got the species"
                    : "⬜ Bonus round — not that one"}
                </div>
              )}
              <div style={styles.revealFacts}>{animal.funFacts}</div>
              <div style={styles.attribution}>{animal.imageAttribution}</div>

              <div style={styles.postcard}>
                <div style={styles.postcardText}>{getShareText()}</div>
                <div style={styles.postcardHint}>tap to select and copy by hand</div>
              </div>
              <button style={styles.shareButton} onClick={copyShareText}>
                {shareCopied ? "Copied!" : "Copy result"}
              </button>

              {/* One aria-label on the anchor: without it the accessible
                  name is the title and body run together as one sentence. */}
              <a
                href="/archive"
                style={styles.archiveCard}
                aria-label="Open your field journal"
              >
                <span style={styles.archiveCardTitle} aria-hidden="true">
                  📔 Your Field Journal →
                </span>
                <span style={styles.archiveCardBody} aria-hidden="true">
                  Every specimen you have identified, and the gaps you have not.
                </span>
              </a>
              <div style={styles.countdownBlock}>
                <div style={styles.countdownLabel}>Next specimen in</div>
                <div style={styles.countdownClock}>{countdown}</div>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}

// ---------- Design tokens & styles ----------
// Palette: warm field-journal paper + coral ink + moss accent.
// Fallback font stacks work without the Framer font setup mentioned above.

const tokens = {
  paper: "#FBF3E7",
  paperCard: "#FFFDF8",
  ink: "#2B2420",
  inkSoft: "#6B5F52",
  coral: "#E8623D",
  coralDark: "#C94E2C",
  moss: "#5C7A5E",
  line: "#E3D5BE",
  display: "'Fraunces', Georgia, serif",
  body: "'Inter', system-ui, -apple-system, sans-serif",
  mono: "'IBM Plex Mono', ui-monospace, SFMono-Regular, monospace",
};

const css = `
  @keyframes stampIn {
    0% { transform: scale(2) rotate(-8deg); opacity: 0; }
    60% { transform: scale(0.95) rotate(-8deg); opacity: 1; }
    100% { transform: scale(1) rotate(-8deg); opacity: 1; }
  }
  @keyframes slideIn {
    from { transform: translateY(8px); opacity: 0; }
    to { transform: translateY(0); opacity: 1; }
  }
`;

const styles: Record<string, CSSProperties> = {
  page: {
    fontFamily: tokens.body,
    background: tokens.paper,
    color: tokens.ink,
    maxWidth: 480,
    margin: "0 auto",
    padding: "24px 20px 40px",
    borderRadius: 16,
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  wordmark: {
    fontFamily: tokens.display,
    fontSize: 24,
    fontWeight: 600,
    letterSpacing: "-0.02em",
  },
  tagline: {
    fontFamily: tokens.mono,
    fontSize: 11,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: tokens.inkSoft,
    marginTop: 2,
  },
  streakBadge: {
    fontFamily: tokens.mono,
    fontSize: 12,
    background: tokens.paperCard,
    border: `1px solid ${tokens.line}`,
    borderRadius: 999,
    padding: "4px 10px",
  },
  headerControls: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  iconTab: {
    fontSize: 14,
    lineHeight: 1,
    background: tokens.paperCard,
    border: `1px solid ${tokens.line}`,
    borderRadius: 6,
    padding: "6px 8px",
    cursor: "pointer",
    color: tokens.ink,
  },
  archivePill: {
    fontFamily: tokens.body,
    fontWeight: 600,
    fontSize: 12,
    color: "#fff",
    background: tokens.coral,
    borderRadius: 999,
    padding: "7px 12px",
    textDecoration: "none",
    whiteSpace: "nowrap",
  },
  statusText: {
    fontFamily: tokens.body,
    color: tokens.inkSoft,
    textAlign: "center",
    padding: "40px 0",
  },
  photoFrame: {
    position: "relative",
    background: tokens.paperCard,
    border: `1px solid ${tokens.line}`,
    borderRadius: 4,
    padding: 10,
    boxShadow: "0 6px 16px rgba(43,36,32,0.08)",
  },
  tapeCorner: {
    position: "absolute",
    top: -8,
    left: 24,
    width: 48,
    height: 18,
    background: "rgba(232,98,61,0.35)",
    transform: "rotate(-6deg)",
    borderRadius: 2,
  },
  photo: {
    width: "100%",
    display: "block",
    borderRadius: 2,
    // `contain`, never `cover`. The photograph IS the puzzle, so cropping it
    // can remove the one feature that makes the animal identifiable — a
    // giraffe loses its neck to a 4:3 landscape crop, a star-nosed mole loses
    // its nose. The fixed aspect ratio stays so the card doesn't jump height
    // between a portrait and a landscape specimen; the letterboxing is
    // deliberate and sits on the card colour.
    objectFit: "contain",
    aspectRatio: "4 / 3",
    background: tokens.paper,
  },
  stamp: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%) rotate(-8deg)",
    fontFamily: tokens.mono,
    fontWeight: 700,
    fontSize: 28,
    letterSpacing: "0.05em",
    color: tokens.coral,
    border: `4px solid ${tokens.coral}`,
    borderRadius: 8,
    padding: "6px 18px",
    background: "rgba(255,253,248,0.85)",
    animation: "stampIn 0.4s ease-out",
  },
  fileTag: {
    fontFamily: tokens.mono,
    fontSize: 12,
    letterSpacing: "0.1em",
    color: tokens.inkSoft,
    textAlign: "center",
    margin: "10px 0 20px",
  },
  dots: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    justifyContent: "center",
    marginBottom: 16,
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: "50%",
    background: tokens.coral,
    display: "inline-block",
  },
  dotsLabel: {
    fontFamily: tokens.mono,
    fontSize: 12,
    color: tokens.inkSoft,
    marginLeft: 6,
  },
  guessRow: {
    display: "flex",
    gap: 8,
    marginBottom: 8,
  },
  input: {
    flex: 1,
    fontFamily: tokens.body,
    fontSize: 15,
    padding: "10px 4px",
    background: "transparent",
    border: "none",
    borderBottom: `2px dashed ${tokens.line}`,
    outline: "none",
    color: tokens.ink,
  },
  guessButton: {
    fontFamily: tokens.body,
    fontWeight: 600,
    fontSize: 14,
    color: "#fff",
    background: tokens.coral,
    border: "none",
    borderRadius: 999,
    padding: "10px 18px",
    cursor: "pointer",
  },
  message: {
    fontFamily: tokens.body,
    fontSize: 13,
    color: tokens.moss,
    marginBottom: 8,
  },
  clues: {
    marginTop: 16,
  },
  cluesLabel: {
    fontFamily: tokens.mono,
    fontSize: 11,
    letterSpacing: "0.1em",
    color: tokens.inkSoft,
    textAlign: "center",
    marginBottom: 10,
  },
  clueCard: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    background: tokens.paperCard,
    border: `1px solid ${tokens.line}`,
    borderRadius: 6,
    padding: "10px 12px",
    marginBottom: 8,
    animation: "slideIn 0.25s ease-out",
  },
  cluePin: {
    fontSize: 13,
  },
  clueLabel: {
    fontFamily: tokens.mono,
    fontSize: 11,
    color: tokens.coral,
    whiteSpace: "nowrap",
  },
  clueText: {
    fontFamily: tokens.body,
    fontSize: 14,
    color: tokens.ink,
  },
  bonusCard: {
    marginTop: 18,
    padding: "16px 14px",
    border: `1px dashed ${tokens.ink}`,
    borderRadius: 8,
  },
  bonusLabel: {
    textAlign: "center",
    letterSpacing: 2,
    fontSize: 12,
    opacity: 0.7,
    marginBottom: 10,
  },
  bonusQuestion: {
    fontSize: 16,
    lineHeight: 1.4,
    marginBottom: 14,
    textAlign: "center",
  },
  bonusResult: {
    fontFamily: tokens.body,
    fontSize: 15,
    fontWeight: 600,
    textAlign: "center",
    marginBottom: 12,
  },
  bonusOptions: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    marginBottom: 12,
  },
  bonusOption: {
    padding: "10px 12px",
    borderRadius: 6,
    border: `1px solid ${tokens.ink}`,
    font: "inherit",
    fontSize: 15,
    // Explicit, not inherited: without it the user agent's own button colour
    // applies, which measured roughly 4:1 against the moss fill on the
    // settled correct answer. `tokens.ink` is what the rest of the card uses.
    color: tokens.ink,
    cursor: "pointer",
    textAlign: "left",
  },
  bonusTally: {
    marginTop: 14,
    fontSize: 14,
    textAlign: "center",
  },
  revealCard: {
    textAlign: "center",
    marginTop: 8,
  },
  revealName: {
    fontFamily: tokens.display,
    fontSize: 26,
    fontWeight: 600,
    marginBottom: 8,
  },
  revealSpecies: {
    fontStyle: "italic",
    opacity: 0.8,
    marginTop: 2,
  },
  revealBonus: {
    marginTop: 8,
    fontSize: 14,
  },
  revealFacts: {
    fontFamily: tokens.body,
    fontSize: 14,
    color: tokens.inkSoft,
    lineHeight: 1.5,
    marginBottom: 10,
  },
  attribution: {
    fontFamily: tokens.mono,
    fontSize: 10,
    color: tokens.inkSoft,
    opacity: 0.8,
    marginBottom: 16,
  },
  postcard: {
    background: tokens.paperCard,
    border: `1px dashed ${tokens.line}`,
    borderRadius: 6,
    padding: "10px 14px",
    marginBottom: 10,
    userSelect: "all",
    cursor: "text",
  },
  postcardText: {
    fontFamily: tokens.mono,
    fontSize: 13,
    color: tokens.ink,
    // The share text carries a newline before the site URL. This postcard is
    // the hand-copy fallback for browsers where navigator.clipboard is
    // unavailable, so what's shown has to match what gets copied — without
    // this, HTML collapses the break and the two diverge.
    whiteSpace: "pre-line",
  },
  postcardHint: {
    fontFamily: tokens.mono,
    fontSize: 10,
    color: tokens.inkSoft,
    marginTop: 4,
  },
  shareButton: {
    fontFamily: tokens.body,
    fontWeight: 600,
    fontSize: 14,
    color: "#fff",
    background: tokens.moss,
    border: "none",
    borderRadius: 999,
    padding: "10px 22px",
    cursor: "pointer",
  },
  countdownBlock: {
    marginTop: 18,
    paddingTop: 14,
    borderTop: `1px dashed ${tokens.line}`,
    textAlign: "center",
  },
  countdownLabel: {
    fontFamily: tokens.mono,
    fontSize: 10,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: tokens.inkSoft,
  },
  countdownClock: {
    fontFamily: tokens.mono,
    fontSize: 24,
    fontWeight: 700,
    letterSpacing: "0.04em",
    color: tokens.ink,
    marginTop: 4,
    // Digits are the same width in a monospace face, so the clock does not
    // jitter as the numbers change every second.
    fontVariantNumeric: "tabular-nums",
  },
  archiveCard: {
    display: "block",
    background: tokens.paperCard,
    border: `1px solid ${tokens.line}`,
    borderRadius: 8,
    padding: "14px 16px",
    marginTop: 20,
    textDecoration: "none",
    textAlign: "left",
  },
  archiveCardTitle: {
    display: "block",
    fontFamily: tokens.body,
    fontWeight: 600,
    fontSize: 15,
    color: tokens.coral,
    marginBottom: 4,
  },
  archiveCardBody: {
    display: "block",
    fontFamily: tokens.body,
    fontSize: 13,
    color: tokens.inkSoft,
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    background: "rgba(43,36,32,0.55)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    zIndex: 9999,
  },
  modalCard: {
    background: tokens.paper,
    border: `1px solid ${tokens.line}`,
    borderRadius: 12,
    boxShadow: "0 18px 44px rgba(43,36,32,0.28)",
    width: "100%",
    maxWidth: 400,
    maxHeight: "85vh",
    display: "flex",
    flexDirection: "column",
    outline: "none",
  },
  modalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 16px 10px",
    borderBottom: `1px solid ${tokens.line}`,
  },
  modalTitle: {
    fontFamily: tokens.mono,
    fontSize: 12,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: tokens.ink,
  },
  modalClose: {
    fontFamily: tokens.body,
    fontSize: 16,
    lineHeight: 1,
    color: tokens.inkSoft,
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: 4,
  },
  modalBody: {
    padding: "16px",
    overflowY: "auto",
  },
  modalFooter: {
    fontFamily: tokens.mono,
    fontSize: 10,
    letterSpacing: "0.1em",
    color: tokens.inkSoft,
    padding: "8px 16px 12px",
    borderTop: `1px solid ${tokens.line}`,
  },
  statsEmpty: {
    fontFamily: tokens.body,
    fontSize: 14,
    color: tokens.inkSoft,
    textAlign: "center",
    padding: "12px 0",
  },
  statsRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 20,
  },
  statsFigure: {
    flex: 1,
    textAlign: "center",
  },
  statsValue: {
    fontFamily: tokens.mono,
    fontSize: 22,
    fontWeight: 700,
    color: tokens.ink,
  },
  statsLabel: {
    fontFamily: tokens.mono,
    fontSize: 9,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: tokens.inkSoft,
    marginTop: 2,
  },
  distTitle: {
    fontFamily: tokens.mono,
    fontSize: 10,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: tokens.inkSoft,
    marginBottom: 8,
  },
  distRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  },
  distIndex: {
    fontFamily: tokens.mono,
    fontSize: 12,
    color: tokens.ink,
    width: 10,
  },
  distBar: {
    height: 18,
    borderRadius: 3,
    display: "inline-block",
    minWidth: 6,
  },
  distCount: {
    fontFamily: tokens.mono,
    fontSize: 11,
    color: tokens.inkSoft,
  },
  howtoSection: {
    marginBottom: 12,
    lineHeight: 1.5,
  },
  howtoHeading: {
    fontFamily: tokens.body,
    fontWeight: 700,
    fontSize: 14,
    color: tokens.ink,
  },
  howtoBody: {
    fontFamily: tokens.body,
    fontSize: 14,
    color: tokens.inkSoft,
  },
  howtoLink: {
    fontFamily: tokens.mono,
    fontSize: 12,
    color: tokens.coral,
    textDecoration: "none",
  },
};
