// WhichAnimalToday — Timer Mode (Framer code component)
//
// Paste this whole file into a Framer code component on its own page. It is
// fully self-contained — Framer's code editor doesn't reliably resolve
// relative imports across pasted files, so the engine is inlined rather than
// imported. That inlined section is GENERATED from src/ by
// scripts/generateFramerEngine.ts: edit src/, then run
// `npm run generate:framer`. Editing it here is overwritten, and both
// `npm test` and CI fail when it drifts. See docs/framer-integration.md.
//
// A survival run: answer as many animals as you can before the clock hits
// zero, by tapping one of four names. Completely separate from the daily
// puzzle — its own storage key, and it can never touch the streak.

const ANIMALS_JSON_URL =
  "https://raw.githubusercontent.com/28-Anon/whichanimaltoday/master/data/animals.json";

const SITE_URL = "https://whichanimaltoday.com";

// Types are imported explicitly rather than reached through a `React.`
// namespace: Framer's code editor doesn't reliably have that namespace in
// scope, so `React.CSSProperties` can fail to compile on paste.
import {
  useCallback,
  useEffect,
  useRef,
  useState,
  type CSSProperties,
} from "react";

// ===== BEGIN GENERATED ENGINE — do not edit by hand =====
// Generated by scripts/generateFramerEngine.ts — do not edit by hand.
// Run `npm run generate:framer` after changing any of:
//   src/stats.ts
//   src/gameState.ts
//   src/timerState.ts
//   src/timerRun.ts
// `npm test` and CI both fail when this block drifts from src/.

// --- from src/stats.ts ---

interface Stats {
  played: number;
  wins: number;
  /** Integer 0-100. 0 when nothing has been played. */
  winPercent: number;
  currentStreak: number;
  maxStreak: number;
  /** Wins on guess 1, 2, and 3 respectively. */
  distribution: [number, number, number];
  /** Days that offered a bonus round and were played. */
  bonusRounds: number;
  /** Of those, the ones the player got right. */
  bonusHits: number;
}

const MS_PER_DAY = 24 * 60 * 60 * 1000;

/** Whole days since the epoch for a YYYY-MM-DD UTC date string. */
function dayNumber(date: string): number {
  return Math.floor(new Date(`${date}T00:00:00Z`).getTime() / MS_PER_DAY);
}

function computeStats(history: DailyResult[], today: string): Stats {
  const sorted = [...history].sort((a, b) => a.date.localeCompare(b.date));

  const played = sorted.length;
  const wins = sorted.filter((entry) => entry.solved).length;
  const winPercent = played === 0 ? 0 : Math.round((wins / played) * 100);

  const distribution: [number, number, number] = [0, 0, 0];
  for (const entry of sorted) {
    if (entry.solved && entry.guessesUsed >= 1 && entry.guessesUsed <= 3) {
      distribution[entry.guessesUsed - 1] += 1;
    }
  }

  // Walk the history once, tracking the run of solved entries on
  // consecutive calendar days. `run` ends up holding the streak that
  // terminates at the most recent entry.
  let maxStreak = 0;
  let run = 0;
  let previous: DailyResult | null = null;
  for (const entry of sorted) {
    if (!entry.solved) {
      run = 0;
    } else if (
      previous !== null &&
      previous.solved &&
      dayNumber(entry.date) - dayNumber(previous.date) === 1
    ) {
      run += 1;
    } else {
      run = 1;
    }
    if (run > maxStreak) maxStreak = run;
    previous = entry;
  }

  // A streak is only alive if the player has actually shown up recently.
  // Nothing is written on days they don't play, so absence has to be
  // detected by comparing against today rather than by a stored counter.
  let currentStreak = 0;
  const last = played === 0 ? null : sorted[played - 1];
  if (last !== null && last.solved) {
    const gap = dayNumber(today) - dayNumber(last.date);
    if (gap === 0 || gap === 1) currentStreak = run;
  }

  // Only the two known values count, so a hand-edited storage value can
  // neither inflate the tally nor throw.
  let bonusRounds = 0;
  let bonusHits = 0;
  for (const entry of sorted) {
    if (entry.bonus === "hit") {
      bonusRounds += 1;
      bonusHits += 1;
    } else if (entry.bonus === "miss") {
      bonusRounds += 1;
    }
  }

  return {
    played,
    wins,
    winPercent,
    currentStreak,
    maxStreak,
    distribution,
    bonusRounds,
    bonusHits,
  };
}

// --- from src/gameState.ts ---

interface StorageLike {
  getItem(key: string): string | null;
  setItem(key: string, value: string): void;
}

interface DailyResult {
  date: string;
  puzzleNumber: number;
  solved: boolean;
  guessesUsed: number;
  /**
   * Absent when the day offered no bonus round. Deliberately does NOT bump
   * SCHEMA_VERSION: `loadState` maps an unrecognised version to an empty
   * history, so a bump would wipe every existing player's stats. An optional
   * field is read correctly by the v2 loader, and a pre-bonus entry having no
   * value here is accurate rather than missing.
   */
  bonus?: "hit" | "miss";
}

const SCHEMA_VERSION = 2;

const STORAGE_KEY = "whichanimaltoday_state";

interface StoredStateV2 {
  version: 2;
  history: DailyResult[];
}

/** The pre-2026-07-29 shape, read only during migration. */
interface StoredStateV1 {
  lastResult: DailyResult | null;
  currentStreak: number;
}

function emptyState(): StoredStateV2 {
  return { version: SCHEMA_VERSION, history: [] };
}

/**
 * A malformed entry (e.g. `null`, or missing/mistyped fields) would
 * otherwise pass the `Array.isArray` check below and then throw later
 * inside `computeStats` (`a.date.localeCompare`) — which, in the Framer
 * component, gets swallowed by the fetch `.catch` and bricks the game on
 * every load thereafter, since nothing ever clears the bad stored value.
 * Filtering here lets a corrupt value self-heal instead.
 */
function isWellFormedEntry(entry: unknown): entry is DailyResult {
  if (typeof entry !== "object" || entry === null) return false;
  const candidate = entry as Partial<DailyResult>;
  return (
    typeof candidate.date === "string" &&
    typeof candidate.solved === "boolean" &&
    typeof candidate.guessesUsed === "number"
  );
}

function loadState(storage: StorageLike): StoredStateV2 {
  let raw: string | null;
  try {
    raw = storage.getItem(STORAGE_KEY);
  } catch {
    // Storage can throw outright rather than return null: blocked cookies
    // and Safari private mode make even reading a SecurityError. Degrade to
    // an empty history so every stat reads zero.
    return emptyState();
  }
  if (!raw) return emptyState();

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return emptyState();
  }
  if (typeof parsed !== "object" || parsed === null) return emptyState();

  const candidate = parsed as Partial<StoredStateV2> & Partial<StoredStateV1>;

  if (candidate.version === SCHEMA_VERSION) {
    return Array.isArray(candidate.history)
      ? {
          version: SCHEMA_VERSION,
          history: candidate.history.filter(isWellFormedEntry),
        }
      : emptyState();
  }

  // v1 -> v2. `currentStreak` is deliberately dropped: the number is known
  // but the days that produced it are not, so it cannot become real
  // history. See spec §2 "Accepted loss".
  if ("lastResult" in candidate) {
    const last = candidate.lastResult;
    return { version: SCHEMA_VERSION, history: last ? [last] : [] };
  }

  return emptyState();
}

function saveState(storage: StorageLike, state: StoredStateV2): void {
  try {
    storage.setItem(STORAGE_KEY, JSON.stringify(state));
  } catch {
    // Quota exceeded, or storage blocked entirely. Nothing to recover: the
    // player gets a fresh game on each load and their stats stay at zero.
    // Throwing here would crash the game the moment they finish a puzzle.
  }
}

function getHistory(storage: StorageLike): DailyResult[] {
  return loadState(storage).history;
}

function getLastResult(storage: StorageLike): DailyResult | null {
  const history = loadState(storage).history;
  if (history.length === 0) return null;
  const sorted = [...history].sort((a, b) => a.date.localeCompare(b.date));
  return sorted[sorted.length - 1];
}

function getCurrentStreak(
  storage: StorageLike,
  today: string
): number {
  return computeStats(loadState(storage).history, today).currentStreak;
}

function getStats(storage: StorageLike, today: string): Stats {
  return computeStats(loadState(storage).history, today);
}

function recordResult(
  storage: StorageLike,
  result: DailyResult
): number {
  // Idempotent by date: re-recording the same day replaces that entry
  // rather than appending, so a double-fire can't inflate `played`.
  const history = loadState(storage).history.filter(
    (entry) => entry.date !== result.date
  );
  history.push(result);
  history.sort((a, b) => a.date.localeCompare(b.date));

  saveState(storage, { version: SCHEMA_VERSION, history });

  // The result being recorded is by definition today's.
  return computeStats(history, result.date).currentStreak;
}

function hasPlayedToday(
  storage: StorageLike,
  today: string
): boolean {
  return loadState(storage).history.some((entry) => entry.date === today);
}

// --- from src/timerState.ts ---

/**
 * Deliberately a third key. Timer mode must never be able to reach the daily
 * history: `loadState` maps an unrecognised version to an empty history, so a
 * shared key means a schema change here could erase a player's streak.
 */
const TIMER_STORAGE_KEY = "whichanimaltoday_timer";

interface TimerStore {
  best: number;
}

function load(storage: StorageLike): TimerStore {
  let raw: string | null;
  try {
    raw = storage.getItem(TIMER_STORAGE_KEY);
  } catch {
    // Storage can throw rather than return null — blocked cookies, private
    // mode. Degrade to "nothing played" rather than breaking the mode.
    return { best: 0 };
  }
  if (!raw) return { best: 0 };

  try {
    const parsed = JSON.parse(raw) as Partial<TimerStore>;
    return typeof parsed?.best === "number" && Number.isFinite(parsed.best)
      ? { best: parsed.best }
      : { best: 0 };
  } catch {
    return { best: 0 };
  }
}

function getBestScore(storage: StorageLike): number {
  return load(storage).best;
}

function recordRun(storage: StorageLike, score: number): number {
  const best = Math.max(load(storage).best, score);
  try {
    storage.setItem(TIMER_STORAGE_KEY, JSON.stringify({ best }));
  } catch {
    // Quota or blocked storage. The run still counts for this session; it
    // just will not survive a reload. Throwing here would end the run.
  }
  return best;
}

// --- from src/timerRun.ts ---

const START_MS = 45_000;

const CORRECT_BONUS_MS = 5_000;

const WRONG_PENALTY_MS = 8_000;

interface QuizAnimal {
  commonName: string;
  category: string;
}

interface TimerQuestion {
  /** Index into the animal list, so the caller can find the image. */
  animalIndex: number;
  options: string[];
  answerIndex: number;
}

interface TimerRun {
  remainingMs: number;
  score: number;
  askedIndexes: number[];
  /** Animal indexes answered wrongly, listed on the end-of-run card. */
  missed: number[];
}

/** mulberry32, matching src/bonusRound.ts — deterministic, tiny, no deps. */
function seededRandom(seed: number): () => number {
  let state = seed >>> 0;
  return function next(): number {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function pick<T>(items: T[], random: () => number): T {
  return items[Math.floor(random() * items.length)];
}

function buildQuestion(
  animals: QuizAnimal[],
  askedIndexes: number[],
  seed: number
): TimerQuestion | null {
  // Four options need four distinct names, so a list shorter than that has no
  // valid question regardless of what has been asked.
  if (animals.length < 4) return null;

  const available = animals
    .map((_, index) => index)
    .filter((index) => !askedIndexes.includes(index));
  if (available.length === 0) return null;

  const random = seededRandom(seed);
  const animalIndex = pick(available, random);
  const answer = animals[animalIndex];

  const sameCategory = animals.filter(
    (a) =>
      a.commonName !== answer.commonName &&
      a.category.toLowerCase() === answer.category.toLowerCase()
  );

  // Same-category decoys are the point — a bird against three other birds.
  // But a thin category cannot fill three, and a repeated option is worse
  // than an easy one, so fall back to the whole list.
  const pool =
    sameCategory.length >= 3
      ? sameCategory
      : animals.filter((a) => a.commonName !== answer.commonName);

  const decoys: string[] = [];
  const seen = new Set<string>([answer.commonName]);
  // Bounded so a pool of duplicate names cannot spin forever.
  for (let attempt = 0; attempt < 200 && decoys.length < 3; attempt++) {
    const candidate = pick(pool, random).commonName;
    if (seen.has(candidate)) continue;
    seen.add(candidate);
    decoys.push(candidate);
  }
  if (decoys.length < 3) return null;

  const options = [...decoys];
  const answerIndex = Math.floor(random() * 4);
  options.splice(answerIndex, 0, answer.commonName);

  return { animalIndex, options, answerIndex };
}

function applyAnswer(
  run: TimerRun,
  correct: boolean,
  question: TimerQuestion
): TimerRun {
  const delta = correct ? CORRECT_BONUS_MS : -WRONG_PENALTY_MS;

  return {
    // Clamped: a negative clock would render as "-3s" and read as a bug.
    remainingMs: Math.max(0, run.remainingMs + delta),
    score: run.score + (correct ? 1 : 0),
    askedIndexes: [...run.askedIndexes, question.animalIndex],
    missed: correct ? [...run.missed] : [...run.missed, question.animalIndex],
  };
}

// ===== END GENERATED ENGINE =====

// ---------- Component-local types and helpers (not generated) ----------

interface Animal {
  commonName: string;
  imageUrl: string;
  category: string;
}

const browserStorage: StorageLike = {
  getItem(key) {
    if (typeof window === "undefined") return null;
    try {
      return window.localStorage.getItem(key);
    } catch {
      return null;
    }
  },
  setItem(key, value) {
    if (typeof window === "undefined") return;
    try {
      window.localStorage.setItem(key, value);
    } catch {
      // Quota exceeded, or storage blocked entirely. The run still counts for
      // this session; the best score just will not survive a reload.
    }
  },
};

/**
 * Resolves true once the image has decoded, false if it failed.
 *
 * The clock runs while a photograph downloads, so on a slow connection that
 * silently eats seconds and reads as the game cheating — and unlike a wrong
 * answer, the player cannot see why.
 *
 * The boolean matters: an unloadable image leaves the player looking at four
 * names and no picture, which is an unanswerable question, not a hard one.
 * The caller skips that animal rather than showing it.
 */
function preload(url: string): Promise<boolean> {
  return new Promise((resolve) => {
    if (typeof window === "undefined") return resolve(false);
    const image = new Image();
    image.onload = () => resolve(true);
    image.onerror = () => resolve(false);
    image.src = url;
  });
}

type Phase = "idle" | "loading" | "error" | "ready" | "asking" | "over";

export default function TimerModeComponent() {
  const [phase, setPhase] = useState<Phase>("loading");
  const [animals, setAnimals] = useState<Animal[]>([]);
  const [best, setBest] = useState(0);

  const [run, setRun] = useState<TimerRun>({
    remainingMs: START_MS,
    score: 0,
    askedIndexes: [],
    missed: [],
  });
  const [question, setQuestion] = useState<TimerQuestion | null>(null);
  const [pick, setPick] = useState<number | null>(null);
  const [remaining, setRemaining] = useState(START_MS);

  // The clock is derived from an absolute deadline, never decremented. A
  // counting-down number drifts, and mobile browsers throttle timers in
  // backgrounded tabs — so a decrementing clock hands free time to anyone who
  // switches apps mid-run, which is the first exploit players find.
  const deadlineRef = useRef<number>(0);
  const pickTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  // The question prefetched while the current one is on screen.
  const preparedRef = useRef<{
    question: TimerQuestion;
    asked: number[];
  } | null>(null);

  useEffect(
    () => () => {
      if (pickTimer.current) clearTimeout(pickTimer.current);
    },
    []
  );

  useEffect(() => {
    setBest(getBestScore(browserStorage));
  }, []);

  useEffect(() => {
    let cancelled = false;

    fetch(ANIMALS_JSON_URL)
      .then((res) => {
        if (!res.ok) throw new Error(`Fetch failed: ${res.status}`);
        return res.json();
      })
      .then((data: Animal[]) => {
        if (cancelled) return;
        if (!Array.isArray(data) || data.length < 4) {
          throw new Error("Not enough animals for a four-option question");
        }
        setAnimals(data);
        setPhase("idle");
      })
      .catch(() => {
        if (!cancelled) setPhase("error");
      });

    return () => {
      cancelled = true;
    };
  }, []);

  const endRun = useCallback((finished: TimerRun) => {
    setRun(finished);
    setRemaining(0);
    setBest(recordRun(browserStorage, finished.score));
    setQuestion(null);
    setPick(null);
    setPhase("over");
  }, []);

  // Ticks only while a question is on screen. Derives the remaining time from
  // the deadline on every frame rather than subtracting, so a throttled or
  // backgrounded tab catches up instantly rather than gaining time.
  useEffect(() => {
    if (phase !== "asking") return;

    function tick() {
      const left = Math.max(0, deadlineRef.current - Date.now());
      setRemaining(left);
      if (left === 0) {
        endRun({ ...runRef.current, remainingMs: 0 });
      }
    }

    tick();
    const timer = setInterval(tick, 200);
    return () => clearInterval(timer);
  }, [phase, endRun]);

  // The tick above reads the run without re-subscribing every time it
  // changes, which would restart the interval on every answer.
  const runRef = useRef(run);
  useEffect(() => {
    runRef.current = run;
  }, [run]);

  /**
   * Builds a question whose image actually loads, skipping any that do not.
   *
   * `asked` accumulates skipped animals as well as answered ones, so a broken
   * image is never offered again for the rest of the run. Bounded, because a
   * whole category of dead URLs must not spin forever.
   */
  const prepare = useCallback(
    async (
      asked: number[]
    ): Promise<{ question: TimerQuestion; asked: number[] } | null> => {
      let attempts = 0;
      let skipped = [...asked];

      while (attempts < 8) {
        attempts += 1;
        const candidate = buildQuestion(animals, skipped, Date.now() + attempts);
        if (!candidate) return null;

        const ok = await preload(animals[candidate.animalIndex].imageUrl);
        if (ok) return { question: candidate, asked: skipped };

        skipped = [...skipped, candidate.animalIndex];
      }
      return null;
    },
    [animals]
  );

  const show = useCallback(
    (next: TimerQuestion, current: TimerRun) => {
      setQuestion(next);
      setPick(null);
      deadlineRef.current = Date.now() + current.remainingMs;
      setRemaining(current.remainingMs);
      setPhase("asking");

      // Prefetch the following question's image while this one is on screen,
      // so answering moves straight to the next photo. Without this every
      // question passed through a "get ready" screen, which unmounted the
      // whole layout and made the page appear to reload between answers.
      void prepare([...current.askedIndexes, next.animalIndex]).then(
        (ready) => {
          preparedRef.current = ready;
        }
      );
    },
    [prepare]
  );

  const askNext = useCallback(
    async (current: TimerRun) => {
      // Use the question prefetched during the previous one, when its asked
      // list still matches — otherwise fall back to preparing one now.
      const ready = preparedRef.current;
      preparedRef.current = null;

      if (ready && !current.askedIndexes.includes(ready.question.animalIndex)) {
        show(ready.question, current);
        return;
      }

      const fresh = await prepare(current.askedIndexes);
      if (!fresh) {
        // Nothing left with a usable image — a completed run, not a timeout.
        endRun(current);
        return;
      }
      show(fresh.question, current);
    },
    [endRun, prepare, show]
  );

  function startRun() {
    preparedRef.current = null;
    setPhase("ready");
    const fresh: TimerRun = {
      remainingMs: START_MS,
      score: 0,
      askedIndexes: [],
      missed: [],
    };
    setRun(fresh);
    askNext(fresh);
  }

  function answer(index: number) {
    if (!question || pick !== null) return;

    setPick(index);
    const correct = index === question.answerIndex;

    // Freeze the clock on the pick rather than letting it run through the
    // feedback beat — the player is not thinking, so they should not be
    // charged for the time.
    const held = Math.max(0, deadlineRef.current - Date.now());
    const next = applyAnswer({ ...run, remainingMs: held }, correct, question);
    setRun(next);

    if (pickTimer.current) clearTimeout(pickTimer.current);
    pickTimer.current = setTimeout(() => {
      if (next.remainingMs <= 0) {
        endRun(next);
      } else {
        askNext(next);
      }
      // Shorter than the daily game's 900ms: a survival run has no time to
      // spare, and the player already knows whether they were right.
    }, 400);
  }

  function shareText(): string {
    return `WhichAnimalToday ⏱ ${run.score} in a row\n${SITE_URL}`;
  }

  const seconds = Math.ceil(remaining / 1000);
  const missedNames = run.missed.map((index) => animals[index]?.commonName);

  return (
    <div style={styles.page}>
      <header style={styles.header}>
        <div>
          <div style={styles.wordmark}>Beat the Clock</div>
          <div style={styles.tagline}>how many can you name?</div>
        </div>
        {best > 0 && <div style={styles.bestBadge}>best {best}</div>}
      </header>

      {phase === "loading" && (
        <div style={styles.statusText}>Loading specimens…</div>
      )}

      {phase === "error" && (
        <div style={styles.statusText}>
          Couldn't load the animals. Please refresh the page.
        </div>
      )}

      {phase === "idle" && (
        <div style={styles.centreCard}>
          <div style={styles.bigNumber}>{START_MS / 1000}s</div>
          <p style={styles.blurb}>
            Name as many specimens as you can. A correct answer adds{" "}
            {CORRECT_BONUS_MS / 1000} seconds; a wrong one costs{" "}
            {WRONG_PENALTY_MS / 1000}.
          </p>
          <button style={styles.primaryButton} onClick={startRun}>
            Start run →
          </button>
        </div>
      )}

      {phase === "ready" && (
        <div style={styles.statusText}>Get ready…</div>
      )}

      {phase === "asking" && question && (
        <>
          <div style={styles.clockRow}>
            <span
              style={{
                ...styles.clock,
                color: seconds <= 10 ? tokens.coral : tokens.ink,
              }}
            >
              {seconds}s
            </span>
            <span style={styles.scorePill}>{run.score} correct</span>
          </div>

          <div style={styles.photoFrame}>
            <img
              src={animals[question.animalIndex].imageUrl}
              alt="Mystery specimen"
              style={styles.photo}
            />
          </div>

          <div style={styles.options}>
            {question.options.map((option, index) => {
              const settled = pick !== null;
              const isAnswer = index === question.answerIndex;
              const picked = pick === index;
              const background = !settled
                ? tokens.paperCard
                : isAnswer
                  ? tokens.moss
                  : picked
                    ? tokens.coral
                    : tokens.paperCard;
              return (
                <button
                  key={option}
                  style={{
                    ...styles.option,
                    background,
                    color: settled && (isAnswer || picked) ? "#fff" : tokens.ink,
                    cursor: settled ? "default" : "pointer",
                  }}
                  aria-disabled={settled}
                  onClick={() => answer(index)}
                >
                  {option}
                </button>
              );
            })}
          </div>
        </>
      )}

      {phase === "over" && (
        <div style={styles.centreCard}>
          <div style={styles.bigNumber}>{run.score}</div>
          <div style={styles.blurb}>
            {run.score === best && run.score > 0
              ? "New best."
              : `Best ${best}.`}
          </div>

          {missedNames.length > 0 && (
            <div style={styles.missedBlock}>
              <div style={styles.missedLabel}>── missed ──</div>
              {missedNames.map((name, i) => (
                <div key={`${name}-${i}`} style={styles.missedName}>
                  {name}
                </div>
              ))}
            </div>
          )}

          <div style={styles.postcard}>
            <div style={styles.postcardText}>{shareText()}</div>
          </div>

          <button style={styles.primaryButton} onClick={startRun}>
            Go again →
          </button>
        </div>
      )}
    </div>
  );
}

// ---------- Design tokens & styles ----------
// Shared with GameComponent.tsx — keep them in sync if the palette changes.

const tokens = {
  paper: "#FBF3E7",
  paperCard: "#FFFDF8",
  ink: "#2B2420",
  inkSoft: "#6B5F52",
  coral: "#E8623D",
  moss: "#5C7A5E",
  line: "#E3D5BE",
  display: "'Fraunces', Georgia, serif",
  body: "'Inter', system-ui, -apple-system, sans-serif",
  mono: "'IBM Plex Mono', ui-monospace, SFMono-Regular, monospace",
};

const styles: Record<string, CSSProperties> = {
  page: {
    fontFamily: tokens.body,
    background: tokens.paper,
    color: tokens.ink,
    width: "100%",
    maxWidth: 480,
    margin: "0 auto",
    padding: "24px 20px 40px",
    borderRadius: 16,
    boxSizing: "border-box",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  wordmark: {
    fontFamily: tokens.display,
    fontSize: 24,
    fontWeight: 600,
    letterSpacing: "-0.02em",
  },
  tagline: {
    fontFamily: tokens.mono,
    fontSize: 11,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: tokens.inkSoft,
    marginTop: 2,
  },
  bestBadge: {
    fontFamily: tokens.mono,
    fontSize: 12,
    background: tokens.paperCard,
    border: `1px solid ${tokens.line}`,
    borderRadius: 999,
    padding: "4px 10px",
  },
  statusText: {
    fontFamily: tokens.body,
    color: tokens.inkSoft,
    textAlign: "center",
    padding: "40px 0",
  },
  centreCard: {
    textAlign: "center",
    padding: "20px 0",
  },
  bigNumber: {
    fontFamily: tokens.display,
    fontSize: 56,
    fontWeight: 600,
    lineHeight: 1,
    marginBottom: 10,
  },
  blurb: {
    fontFamily: tokens.body,
    fontSize: 14,
    color: tokens.inkSoft,
    lineHeight: 1.5,
    margin: "0 auto 18px",
    maxWidth: 320,
  },
  primaryButton: {
    fontFamily: tokens.body,
    fontWeight: 600,
    fontSize: 14,
    color: "#fff",
    background: tokens.coral,
    border: "none",
    borderRadius: 999,
    padding: "12px 24px",
    cursor: "pointer",
  },
  clockRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  clock: {
    fontFamily: tokens.mono,
    fontSize: 30,
    fontWeight: 700,
    // Digits are the same width in a monospace face, so the clock does not
    // jitter as the numbers change.
    fontVariantNumeric: "tabular-nums",
  },
  scorePill: {
    fontFamily: tokens.mono,
    fontSize: 12,
    background: tokens.paperCard,
    border: `1px solid ${tokens.line}`,
    borderRadius: 999,
    padding: "4px 10px",
  },
  photoFrame: {
    background: tokens.paperCard,
    border: `1px solid ${tokens.line}`,
    borderRadius: 4,
    padding: 8,
    marginBottom: 14,
  },
  photo: {
    width: "100%",
    display: "block",
    borderRadius: 2,
    // `contain`, never `cover`: cropping can remove the one feature that makes
    // the animal identifiable, which in a guessing game is the whole puzzle.
    objectFit: "contain",
    aspectRatio: "4 / 3",
    background: tokens.paper,
  },
  options: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  option: {
    fontFamily: tokens.body,
    fontSize: 15,
    padding: "12px 14px",
    borderRadius: 6,
    border: `1px solid ${tokens.line}`,
    textAlign: "left",
  },
  missedBlock: {
    margin: "18px 0",
  },
  missedLabel: {
    fontFamily: tokens.mono,
    fontSize: 11,
    letterSpacing: "0.1em",
    color: tokens.inkSoft,
    marginBottom: 8,
  },
  missedName: {
    fontFamily: tokens.body,
    fontSize: 14,
    color: tokens.inkSoft,
  },
  postcard: {
    background: tokens.paperCard,
    border: `1px dashed ${tokens.line}`,
    borderRadius: 6,
    padding: "10px 14px",
    margin: "0 0 14px",
    userSelect: "all",
    cursor: "text",
  },
  postcardText: {
    fontFamily: tokens.mono,
    fontSize: 13,
    color: tokens.ink,
    whiteSpace: "pre-line",
  },
};
