import ts from "typescript";

export interface EngineModule {
  /** Repo-relative path. Used in from-markers and error messages. */
  path: string;
  source: string;
}

function parse(path: string, source: string): ts.SourceFile {
  return ts.createSourceFile(
    path,
    source,
    ts.ScriptTarget.ES2020,
    // Parent pointers are needed so getStart(sourceFile) works on modifiers.
    true,
    path.endsWith(".tsx") ? ts.ScriptKind.TSX : ts.ScriptKind.TS
  );
}

/** Every top-level name a statement binds, in source order. */
function declaredNames(statement: ts.Statement): string[] {
  if (
    ts.isFunctionDeclaration(statement) ||
    ts.isClassDeclaration(statement) ||
    ts.isInterfaceDeclaration(statement) ||
    ts.isTypeAliasDeclaration(statement) ||
    ts.isEnumDeclaration(statement)
  ) {
    return statement.name ? [statement.name.text] : [];
  }
  if (ts.isVariableStatement(statement)) {
    return statement.declarationList.declarations
      .map((declaration) =>
        ts.isIdentifier(declaration.name) ? declaration.name.text : null
      )
      .filter((name): name is string => name !== null);
  }
  return [];
}

/**
 * The statement's own text, including any leading comment, with the
 * `export` modifier removed by AST position rather than by string match.
 */
function statementText(
  statement: ts.Statement,
  sourceFile: ts.SourceFile
): string {
  const source = sourceFile.text;
  const start = statement.getFullStart();
  const end = statement.getEnd();

  const exportModifier = ts.canHaveModifiers(statement)
    ? ts
        .getModifiers(statement)
        ?.find((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword)
    : undefined;

  if (!exportModifier) return source.slice(start, end).trim();

  const head = source.slice(start, exportModifier.getStart(sourceFile));
  // Only spaces and tabs, so `export` on its own line stays on its own line.
  const tail = source
    .slice(exportModifier.getEnd(), end)
    .replace(/^[ \t]+/, "");
  return (head + tail).trim();
}

export function topLevelNames(path: string, source: string): string[] {
  return parse(path, source).statements.flatMap(declaredNames);
}

export function renderEngineBlock(modules: EngineModule[]): string {
  const seen = new Map<string, { text: string; modulePath: string }>();
  const sections: { path: string; texts: string[] }[] = [];

  for (const module of modules) {
    const sourceFile = parse(module.path, module.source);
    const texts: string[] = [];

    for (const statement of sourceFile.statements) {
      if (
        ts.isImportDeclaration(statement) ||
        ts.isExportDeclaration(statement)
      ) {
        continue;
      }

      const names = declaredNames(statement);
      const text = statementText(statement, sourceFile);

      if (names.length > 0) {
        const key = names.join(",");
        const previous = seen.get(key);
        if (previous) {
          // Identical redeclaration across modules (MS_PER_DAY lives in both
          // src/puzzleIndex.ts and src/stats.ts). Emitting it twice would be
          // a duplicate-const syntax error, so keep the first.
          if (previous.text === text) continue;
          throw new Error(
            `Conflicting declarations of \`${key}\`: ${previous.modulePath} ` +
              `and ${module.path} declare it differently. Reconcile them in ` +
              `src/ before generating.`
          );
        }
        seen.set(key, { text, modulePath: module.path });
      }

      texts.push(text);
    }

    if (texts.length > 0) sections.push({ path: module.path, texts });
  }

  const header = [
    "// Generated by scripts/generateFramerEngine.ts — do not edit by hand.",
    "// Run `npm run generate:framer` after changing any of:",
    ...modules.map((module) => `//   ${module.path}`),
    "// `npm test` and CI both fail when this block drifts from src/.",
  ].join("\n");

  const body = sections
    .map((section) =>
      [`// --- from ${section.path} ---`, ...section.texts].join("\n\n")
    )
    .join("\n\n");

  return `${header}\n\n${body}\n`;
}
